-- Generated by Luotain (https://github.com/anttiluode/Luotain). Core Lean 4, no Mathlib.
set_option maxHeartbeats 1000000
set_option maxRecDepth 100000
set_option linter.unusedVariables false
set_option maxErrors 100000


namespace Luotain.Calibration



abbrev E14 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op y (op x y)

abbrev E57 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op y (op y z))

abbrev E68 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op x (op z x))

abbrev E126 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op y x) z)

abbrev E186 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y z) (op x x)

abbrev E211 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op x (op y y)) x

abbrev E219 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op y (op x x)) y

abbrev E253 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op z w)) w

abbrev E258 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op x x) y) y

abbrev E308 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op x (op x y)

abbrev E354 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op z (op w x)

abbrev E406 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op (op z w) x

abbrev E448 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op y (op z (op x z)))

abbrev E506 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op y (op x (op z x)))

abbrev E520 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op y (op z (op x x)))

abbrev E527 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op y (op z (op y w)))

abbrev E550 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op z (op x (op w y)))

abbrev E583 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op z (op z (op w x)))

abbrev E709 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op y (op (op x z) x))

abbrev E746 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op z (op (op x y) z))

abbrev E834 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op (op y x) (op x z))

abbrev E835 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op x (op (op y x) (op y x))

abbrev E842 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op x (op (op y y) (op x x))

abbrev E849 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op (op y y) (op z y))

abbrev E860 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op (op y z) (op z x))

abbrev E963 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op (op z y) (op x w))

abbrev E988 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op (op z z) (op z w))

abbrev E999 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op (op z w) (op y x))

abbrev E1040 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op (op y (op x y)) z)

abbrev E1107 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op (op x (op z w)) w)

abbrev E1189 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op z (op z z)) y)

abbrev E1232 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op x (op (op (op x y) y) y)

abbrev E1241 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op x (op (op (op y x) y) x)

abbrev E1296 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op (op x z) x) y)

abbrev E1300 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op (op x z) y) y)

abbrev E1577 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y z) (op y (op z x))

abbrev E1602 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op y z) (op z (op w u))

abbrev E1658 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op x y) (op (op y y) y)

abbrev E1664 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x y) (op (op z x) x)

abbrev E1707 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y x) (op (op z y) z)

abbrev E1819 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y z) (op (op w z) w)

abbrev E1821 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y z) (op (op w w) x)

abbrev E1867 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x (op y z)) (op x x)

abbrev E1885 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op y (op x x)) (op x y)

abbrev E1890 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op x x)) (op z x)

abbrev E1898 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op y (op x y)) (op y y)

abbrev E2049 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op x x) y) (op z w)

abbrev E2082 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op x y) z) (op w x)

abbrev E2092 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y x) x) (op y z)

abbrev E2103 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y x) y) (op z x)

abbrev E2137 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op y y) y) (op y x)

abbrev E2170 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y z) x) (op z y)

abbrev E2195 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y z) z) (op x x)

abbrev E2206 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op y z) z) (op z w)

abbrev E2237 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u v : α, x = op (op (op y z) w) (op u v)

abbrev E2280 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op x (op y (op z y))) w

abbrev E2302 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op x (op y x))) z

abbrev E2303 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op y (op x (op y y))) x

abbrev E2305 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op x (op y y))) z

abbrev E2488 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op x (op (op y z) w)) x

abbrev E2507 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op y (op (op x y) y)) y

abbrev E2517 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op (op x z) y)) x

abbrev E2546 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op (op y y) z)) x

abbrev E2613 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op (op z z) w)) x

abbrev E2666 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op x y) (op x z)) y

abbrev E2697 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op y x) (op x x)) y

abbrev E2704 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y x) (op x z)) z

abbrev E2763 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y y) (op z z)) z

abbrev E2851 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op x (op x x)) y) z

abbrev E2862 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op x (op y x)) x) x

abbrev E2866 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op x (op y x)) y) y

abbrev E2869 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op x (op y x)) z) y

abbrev E2880 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op x (op y y)) z) z

abbrev E2984 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op y (op z x)) z) w

abbrev E3040 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op y (op z w)) w) y

abbrev E3085 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op x y) z) x) x

abbrev E3093 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op x y) z) z) x

abbrev E3319 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x y = op x (op y (op y y))

abbrev E3322 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op x (op y (op z y))

abbrev E3342 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x y = op y (op x (op x x))

abbrev E3371 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op y (op z (op z y))

abbrev E3380 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op z (op x (op x y))

abbrev E3389 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op z (op x (op z z))

abbrev E3471 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op y (op (op x x) x)

abbrev E3502 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x x = op y (op (op z z) w)

abbrev E3515 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op x (op (op x z) y)

abbrev E3524 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op x (op (op y z) x)

abbrev E3626 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op z (op (op z z) z)

abbrev E3648 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op z (op (op w w) x)

abbrev E3652 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op x y = op z (op (op w w) u)

abbrev E3674 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op (op y x) (op x x)

abbrev E3811 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op z y) (op z y)

abbrev E3828 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op z z) (op z y)

abbrev E3831 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op (op z z) (op w x)

abbrev E3870 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op (op x (op y y)) x

abbrev E3876 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x x = op (op x (op y z)) w

abbrev E3931 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op x (op y z)) y

abbrev E3969 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op y (op y z)) z

abbrev E4117 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x y = op (op (op x x) x) x

abbrev E4155 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x y = op (op (op y x) x) y

abbrev E4190 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op x y = op (op (op y z) w) u

abbrev E4227 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op (op z z) x) z

abbrev E4294 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op x y) = op y (op y z)

abbrev E4295 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op x y) = op y (op z x)

abbrev E4300 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op x y) = op z (op x y)

abbrev E4330 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y x) = op z (op y x)

abbrev E4385 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x (op x x) = op (op y x) x

abbrev E4414 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op x y) = op (op y z) w

abbrev E4466 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op y x) = op (op z w) z

abbrev E4480 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x (op y y) = op (op y x) y

abbrev E4529 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y z) = op (op y y) z

abbrev E4590 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op (op x x) x = op (op y y) x

abbrev E4602 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x x) y = op (op x z) y

abbrev E4610 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x x) y = op (op y z) x

abbrev E4612 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x x) y = op (op y z) z

abbrev E4634 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op (op x y) x = op (op x z) w

abbrev E4666 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x y) y = op (op z y) y

abbrev E4672 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op (op x y) z = op (op x y) w



def P0_tbl : List Nat := [0, 1, 0, 1]
def P0 (a b : Fin 2) : Fin 2 := ⟨(P0_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P1_tbl : List Nat := [0, 0, 0, 0, 0, 0, 0, 0, 1]
def P1 (a b : Fin 3) : Fin 3 := ⟨(P1_tbl.getD (3 * a.val + b.val) 0) % 3, Nat.mod_lt _ (by decide)⟩

def P2_tbl : List Nat := [0, 0, 0, 0]
def P2 (a b : Fin 2) : Fin 2 := ⟨(P2_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P3_tbl : List Nat := [0, 0, 1, 0]
def P3 (a b : Fin 2) : Fin 2 := ⟨(P3_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P4_tbl : List Nat := [0, 0, 1, 1]
def P4 (a b : Fin 2) : Fin 2 := ⟨(P4_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P5_tbl : List Nat := [0, 1, 1, 0]
def P5 (a b : Fin 2) : Fin 2 := ⟨(P5_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P6_tbl : List Nat := [0, 2, 1, 2, 1, 0, 1, 0, 2]
def P6 (a b : Fin 3) : Fin 3 := ⟨(P6_tbl.getD (3 * a.val + b.val) 0) % 3, Nat.mod_lt _ (by decide)⟩

def P7_tbl : List Nat := [0, 0, 0, 1]
def P7 (a b : Fin 2) : Fin 2 := ⟨(P7_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P8_tbl : List Nat := [0, 0, 0, 0, 0, 0, 0, 1, 0]
def P8 (a b : Fin 3) : Fin 3 := ⟨(P8_tbl.getD (3 * a.val + b.val) 0) % 3, Nat.mod_lt _ (by decide)⟩

def P9_tbl : List Nat := [0, 1, 0, 0]
def P9 (a b : Fin 2) : Fin 2 := ⟨(P9_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P10_tbl : List Nat := [1, 0, 1, 0]
def P10 (a b : Fin 2) : Fin 2 := ⟨(P10_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩



theorem not_1664_57 : ¬ ∀ (α : Type) (op : α → α → α), E1664 op → E57 op := by
  intro h
  have hb : ¬ E57 P0 := by unfold E57; decide
  exact hb (h (Fin 2) P0 (by unfold E1664; decide))

theorem not_4294_3389 : ¬ ∀ (α : Type) (op : α → α → α), E4294 op → E3389 op := by
  intro h
  have hb : ¬ E3389 P1 := by unfold E3389; decide
  exact hb (h (Fin 3) P1 (by unfold E4294; decide))

theorem not_3648_520 : ¬ ∀ (α : Type) (op : α → α → α), E3648 op → E520 op := by
  intro h
  have hb : ¬ E520 P2 := by unfold E520; decide
  exact hb (h (Fin 2) P2 (by unfold E3648; decide))

theorem not_842_1107 : ¬ ∀ (α : Type) (op : α → α → α), E842 op → E1107 op := by
  intro h
  have hb : ¬ E1107 P3 := by unfold E1107; decide
  exact hb (h (Fin 2) P3 (by unfold E842; decide))

theorem not_1040_2170 : ¬ ∀ (α : Type) (op : α → α → α), E1040 op → E2170 op := by
  intro h
  have hb : ¬ E2170 P4 := by unfold E2170; decide
  exact hb (h (Fin 2) P4 (by unfold E1040; decide))

theorem not_4602_2862 : ¬ ∀ (α : Type) (op : α → α → α), E4602 op → E2862 op := by
  intro h
  have hb : ¬ E2862 P2 := by unfold E2862; decide
  exact hb (h (Fin 2) P2 (by unfold E4602; decide))

theorem not_1707_4466 : ¬ ∀ (α : Type) (op : α → α → α), E1707 op → E4466 op := by
  intro h
  have hb : ¬ E4466 P5 := by unfold E4466; decide
  exact hb (h (Fin 2) P5 (by unfold E1707; decide))

theorem not_4385_963 : ¬ ∀ (α : Type) (op : α → α → α), E4385 op → E963 op := by
  intro h
  have hb : ¬ E963 P2 := by unfold E963; decide
  exact hb (h (Fin 2) P2 (by unfold E4385; decide))

theorem not_2488_68 : ¬ ∀ (α : Type) (op : α → α → α), E2488 op → E68 op := by
  intro h
  have hb : ¬ E68 P4 := by unfold E68; decide
  exact hb (h (Fin 2) P4 (by unfold E2488; decide))

theorem not_4529_1300 : ¬ ∀ (α : Type) (op : α → α → α), E4529 op → E1300 op := by
  intro h
  have hb : ¬ E1300 P2 := by unfold E1300; decide
  exact hb (h (Fin 2) P2 (by unfold E4529; decide))

theorem not_2280_3040 : ¬ ∀ (α : Type) (op : α → α → α), E2280 op → E3040 op := by
  intro h
  have hb : ¬ E3040 P4 := by unfold E3040; decide
  exact hb (h (Fin 2) P4 (by unfold E2280; decide))

theorem not_1885_2851 : ¬ ∀ (α : Type) (op : α → α → α), E1885 op → E2851 op := by
  intro h
  have hb : ¬ E2851 P5 := by unfold E2851; decide
  exact hb (h (Fin 2) P5 (by unfold E1885; decide))

theorem not_3371_2546 : ¬ ∀ (α : Type) (op : α → α → α), E3371 op → E2546 op := by
  intro h
  have hb : ¬ E2546 P2 := by unfold E2546; decide
  exact hb (h (Fin 2) P2 (by unfold E3371; decide))

theorem not_2507_999 : ¬ ∀ (α : Type) (op : α → α → α), E2507 op → E999 op := by
  intro h
  have hb : ¬ E999 P5 := by unfold E999; decide
  exact hb (h (Fin 2) P5 (by unfold E2507; decide))

theorem not_3931_1189 : ¬ ∀ (α : Type) (op : α → α → α), E3931 op → E1189 op := by
  intro h
  have hb : ¬ E1189 P2 := by unfold E1189; decide
  exact hb (h (Fin 2) P2 (by unfold E3931; decide))

theorem not_2103_2305 : ¬ ∀ (α : Type) (op : α → α → α), E2103 op → E2305 op := by
  intro h
  have hb : ¬ E2305 P0 := by unfold E2305; decide
  exact hb (h (Fin 2) P0 (by unfold E2103; decide))

theorem not_2049_583 : ¬ ∀ (α : Type) (op : α → α → α), E2049 op → E583 op := by
  intro h
  have hb : ¬ E583 P4 := by unfold E583; decide
  exact hb (h (Fin 2) P4 (by unfold E2049; decide))

theorem not_1658_834 : ¬ ∀ (α : Type) (op : α → α → α), E1658 op → E834 op := by
  intro h
  have hb : ¬ E834 P5 := by unfold E834; decide
  exact hb (h (Fin 2) P5 (by unfold E1658; decide))

theorem not_219_4634 : ¬ ∀ (α : Type) (op : α → α → α), E219 op → E4634 op := by
  intro h
  have hb : ¬ E4634 P6 := by unfold E4634; decide
  exact hb (h (Fin 3) P6 (by unfold E219; decide))

theorem not_3322_1296 : ¬ ∀ (α : Type) (op : α → α → α), E3322 op → E1296 op := by
  intro h
  have hb : ¬ E1296 P2 := by unfold E1296; decide
  exact hb (h (Fin 2) P2 (by unfold E3322; decide))

theorem not_3085_2302 : ¬ ∀ (α : Type) (op : α → α → α), E3085 op → E2302 op := by
  intro h
  have hb : ¬ E2302 P4 := by unfold E2302; decide
  exact hb (h (Fin 2) P4 (by unfold E3085; decide))

theorem not_3828_746 : ¬ ∀ (α : Type) (op : α → α → α), E3828 op → E746 op := by
  intro h
  have hb : ¬ E746 P2 := by unfold E746; decide
  exact hb (h (Fin 2) P2 (by unfold E3828; decide))

theorem not_709_1898 : ¬ ∀ (α : Type) (op : α → α → α), E709 op → E1898 op := by
  intro h
  have hb : ¬ E1898 P0 := by unfold E1898; decide
  exact hb (h (Fin 2) P0 (by unfold E709; decide))

theorem not_3342_211 : ¬ ∀ (α : Type) (op : α → α → α), E3342 op → E211 op := by
  intro h
  have hb : ¬ E211 P2 := by unfold E211; decide
  exact hb (h (Fin 2) P2 (by unfold E3342; decide))

theorem not_3524_4612 : ¬ ∀ (α : Type) (op : α → α → α), E3524 op → E4612 op := by
  intro h
  have hb : ¬ E4612 P4 := by unfold E4612; decide
  exact hb (h (Fin 2) P4 (by unfold E3524; decide))

theorem not_4666_1890 : ¬ ∀ (α : Type) (op : α → α → α), E4666 op → E1890 op := by
  intro h
  have hb : ¬ E1890 P2 := by unfold E1890; decide
  exact hb (h (Fin 2) P2 (by unfold E4666; decide))

theorem not_849_3380 : ¬ ∀ (α : Type) (op : α → α → α), E849 op → E3380 op := by
  intro h
  have hb : ¬ E3380 P3 := by unfold E3380; decide
  exact hb (h (Fin 2) P3 (by unfold E849; decide))

theorem not_1821_2206 : ¬ ∀ (α : Type) (op : α → α → α), E1821 op → E2206 op := by
  intro h
  have hb : ¬ E2206 P0 := by unfold E2206; decide
  exact hb (h (Fin 2) P0 (by unfold E1821; decide))

theorem not_3870_4672 : ¬ ∀ (α : Type) (op : α → α → α), E3870 op → E4672 op := by
  intro h
  have hb : ¬ E4672 P3 := by unfold E4672; decide
  exact hb (h (Fin 2) P3 (by unfold E3870; decide))

theorem not_506_988 : ¬ ∀ (α : Type) (op : α → α → α), E506 op → E988 op := by
  intro h
  have hb : ¬ E988 P0 := by unfold E988; decide
  exact hb (h (Fin 2) P0 (by unfold E506; decide))

theorem not_2866_126 : ¬ ∀ (α : Type) (op : α → α → α), E2866 op → E126 op := by
  intro h
  have hb : ¬ E126 P4 := by unfold E126; decide
  exact hb (h (Fin 2) P4 (by unfold E2866; decide))

theorem not_2880_2869 : ¬ ∀ (α : Type) (op : α → α → α), E2880 op → E2869 op := by
  intro h
  have hb : ¬ E2869 P5 := by unfold E2869; decide
  exact hb (h (Fin 2) P5 (by unfold E2880; decide))

theorem not_1241_2763 : ¬ ∀ (α : Type) (op : α → α → α), E1241 op → E2763 op := by
  intro h
  have hb : ¬ E2763 P3 := by unfold E2763; decide
  exact hb (h (Fin 2) P3 (by unfold E1241; decide))

theorem not_258_406 : ¬ ∀ (α : Type) (op : α → α → α), E258 op → E406 op := by
  intro h
  have hb : ¬ E406 P4 := by unfold E406; decide
  exact hb (h (Fin 2) P4 (by unfold E258; decide))

theorem not_3674_253 : ¬ ∀ (α : Type) (op : α → α → α), E3674 op → E253 op := by
  intro h
  have hb : ¬ E253 P2 := by unfold E253; decide
  exact hb (h (Fin 2) P2 (by unfold E3674; decide))

theorem not_3093_3831 : ¬ ∀ (α : Type) (op : α → α → α), E3093 op → E3831 op := by
  intro h
  have hb : ¬ E3831 P4 := by unfold E3831; decide
  exact hb (h (Fin 2) P4 (by unfold E3093; decide))

theorem not_3652_2984 : ¬ ∀ (α : Type) (op : α → α → α), E3652 op → E2984 op := by
  intro h
  have hb : ¬ E2984 P2 := by unfold E2984; decide
  exact hb (h (Fin 2) P2 (by unfold E3652; decide))

theorem not_3342_4414 : ¬ ∀ (α : Type) (op : α → α → α), E3342 op → E4414 op := by
  intro h
  have hb : ¬ E4414 P7 := by unfold E4414; decide
  exact hb (h (Fin 2) P7 (by unfold E3342; decide))

theorem not_448_3626 : ¬ ∀ (α : Type) (op : α → α → α), E448 op → E3626 op := by
  intro h
  have hb : ¬ E3626 P4 := by unfold E3626; decide
  exact hb (h (Fin 2) P4 (by unfold E448; decide))

theorem not_3319_2666 : ¬ ∀ (α : Type) (op : α → α → α), E3319 op → E2666 op := by
  intro h
  have hb : ¬ E2666 P2 := by unfold E2666; decide
  exact hb (h (Fin 2) P2 (by unfold E3319; decide))

theorem not_3471_4300 : ¬ ∀ (α : Type) (op : α → α → α), E3471 op → E4300 op := by
  intro h
  have hb : ¬ E4300 P8 := by unfold E4300; decide
  exact hb (h (Fin 3) P8 (by unfold E3471; decide))

theorem not_14_2092 : ¬ ∀ (α : Type) (op : α → α → α), E14 op → E2092 op := by
  intro h
  have hb : ¬ E2092 P5 := by unfold E2092; decide
  exact hb (h (Fin 2) P5 (by unfold E14; decide))

theorem not_308_3811 : ¬ ∀ (α : Type) (op : α → α → α), E308 op → E3811 op := by
  intro h
  have hb : ¬ E3811 P4 := by unfold E3811; decide
  exact hb (h (Fin 2) P4 (by unfold E308; decide))

theorem not_2697_2704 : ¬ ∀ (α : Type) (op : α → α → α), E2697 op → E2704 op := by
  intro h
  have hb : ¬ E2704 P5 := by unfold E2704; decide
  exact hb (h (Fin 2) P5 (by unfold E2697; decide))

theorem not_2082_1819 : ¬ ∀ (α : Type) (op : α → α → α), E2082 op → E1819 op := by
  intro h
  have hb : ¬ E1819 P4 := by unfold E1819; decide
  exact hb (h (Fin 2) P4 (by unfold E2082; decide))

theorem not_4330_2137 : ¬ ∀ (α : Type) (op : α → α → α), E4330 op → E2137 op := by
  intro h
  have hb : ¬ E2137 P2 := by unfold E2137; decide
  exact hb (h (Fin 2) P2 (by unfold E4330; decide))

theorem not_2303_1602 : ¬ ∀ (α : Type) (op : α → α → α), E2303 op → E1602 op := by
  intro h
  have hb : ¬ E1602 P9 := by unfold E1602; decide
  exact hb (h (Fin 2) P9 (by unfold E2303; decide))

theorem not_3502_550 : ¬ ∀ (α : Type) (op : α → α → α), E3502 op → E550 op := by
  intro h
  have hb : ¬ E550 P2 := by unfold E550; decide
  exact hb (h (Fin 2) P2 (by unfold E3502; decide))

theorem not_1577_3876 : ¬ ∀ (α : Type) (op : α → α → α), E1577 op → E3876 op := by
  intro h
  have hb : ¬ E3876 P0 := by unfold E3876; decide
  exact hb (h (Fin 2) P0 (by unfold E1577; decide))

theorem not_860_2237 : ¬ ∀ (α : Type) (op : α → α → α), E860 op → E2237 op := by
  intro h
  have hb : ¬ E2237 P4 := by unfold E2237; decide
  exact hb (h (Fin 2) P4 (by unfold E860; decide))

theorem not_186_4480 : ¬ ∀ (α : Type) (op : α → α → α), E186 op → E4480 op := by
  intro h
  have hb : ¬ E4480 P10 := by unfold E4480; decide
  exact hb (h (Fin 2) P10 (by unfold E186; decide))

theorem not_835_3969 : ¬ ∀ (α : Type) (op : α → α → α), E835 op → E3969 op := by
  intro h
  have hb : ¬ E3969 P3 := by unfold E3969; decide
  exact hb (h (Fin 2) P3 (by unfold E835; decide))

theorem not_4295_4155 : ¬ ∀ (α : Type) (op : α → α → α), E4295 op → E4155 op := by
  intro h
  have hb : ¬ E4155 P1 := by unfold E4155; decide
  exact hb (h (Fin 3) P1 (by unfold E4295; decide))

theorem not_354_2195 : ¬ ∀ (α : Type) (op : α → α → α), E354 op → E2195 op := by
  intro h
  have hb : ¬ E2195 P2 := by unfold E2195; decide
  exact hb (h (Fin 2) P2 (by unfold E354; decide))

theorem not_3515_2517 : ¬ ∀ (α : Type) (op : α → α → α), E3515 op → E2517 op := by
  intro h
  have hb : ¬ E2517 P2 := by unfold E2517; decide
  exact hb (h (Fin 2) P2 (by unfold E3515; decide))

theorem not_4227_2613 : ¬ ∀ (α : Type) (op : α → α → α), E4227 op → E2613 op := by
  intro h
  have hb : ¬ E2613 P2 := by unfold E2613; decide
  exact hb (h (Fin 2) P2 (by unfold E4227; decide))

theorem not_4590_1867 : ¬ ∀ (α : Type) (op : α → α → α), E4590 op → E1867 op := by
  intro h
  have hb : ¬ E1867 P2 := by unfold E1867; decide
  exact hb (h (Fin 2) P2 (by unfold E4590; decide))

theorem not_4610_4190 : ¬ ∀ (α : Type) (op : α → α → α), E4610 op → E4190 op := by
  intro h
  have hb : ¬ E4190 P1 := by unfold E4190; decide
  exact hb (h (Fin 3) P1 (by unfold E4610; decide))

theorem not_3371_527 : ¬ ∀ (α : Type) (op : α → α → α), E3371 op → E527 op := by
  intro h
  have hb : ¬ E527 P2 := by unfold E527; decide
  exact hb (h (Fin 2) P2 (by unfold E3371; decide))

theorem not_4117_1232 : ¬ ∀ (α : Type) (op : α → α → α), E4117 op → E1232 op := by
  intro h
  have hb : ¬ E1232 P2 := by unfold E1232; decide
  exact hb (h (Fin 2) P2 (by unfold E4117; decide))



end Luotain.Calibration
