-- Generated by Luotain (https://github.com/anttiluode/Luotain). Core Lean 4, no Mathlib.
set_option maxHeartbeats 1000000
set_option maxRecDepth 100000
set_option linter.unusedVariables false
set_option maxErrors 100000


namespace Luotain.Collapse



abbrev E2 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = y

abbrev E4975 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op x (op z (op x (op x w))))

abbrev E5349 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op y (op z (op y (op w (op u y))))

abbrev E6161 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op z (op y (op (op x y) w)))

abbrev E6242 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op z (op z (op (op x z) w)))

abbrev E6330 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op y (op z (op w (op (op x u) z)))

abbrev E6875 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op y (op (op y z) (op w w)))

abbrev E7172 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op z (op (op z w) (op z w)))

abbrev E7260 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op y (op z (op (op w z) (op u w)))

abbrev E7616 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op x (op (op z (op x w)) y))

abbrev E7931 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op z (op (op y (op y y)) z))

abbrev E8097 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op y (op z (op (op w (op y y)) u))

abbrev E8588 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op y (op (op (op x z) z) w))

abbrev E9076 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u v : α, x = op y (op z (op (op (op w u) v) w))

abbrev E9613 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op (op z x) (op y (op z w)))

abbrev E10516 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op (op z x) (op (op w x) w))

abbrev E11135 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op (op x (op z y)) (op y w))

abbrev E12435 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op y (op (op (op z z) w) (op z u))

abbrev E12887 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op x (op z (op y y))) y)

abbrev E13111 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op z (op x (op y x))) y)

abbrev E13364 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op y (op (op z (op w (op y z))) u)

abbrev E15002 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op (op z z) (op x x)) y)

abbrev E15077 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u v : α, x = op y (op (op (op z z) (op w u)) v)

abbrev E15619 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op (op (op y (op y x)) z) w)

abbrev E16810 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op y (op (op (op (op z z) w) x) u)

abbrev E16958 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op y (op (op (op (op z w) u) w) u)

abbrev E18939 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y x) (op (op x x) (op z w))

abbrev E19519 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op y z) (op (op w z) (op x u))

abbrev E19946 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op y x) (op (op z (op w z)) u)

abbrev E20110 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y z) (op (op x (op x x)) y)

abbrev E20168 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y z) (op (op x (op w y)) w)

abbrev E20821 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y x) (op (op (op z w) z) z)

abbrev E20972 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y y) (op (op (op z w) z) z)

abbrev E21579 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op x x)) (op y (op z z))

abbrev E21584 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op x x)) (op z (op x w))

abbrev E21804 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op y z)) (op y (op x y))

abbrev E22016 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u v : α, x = op (op y (op z y)) (op w (op u v))

abbrev E22181 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op y (op z w)) (op w (op y u))

abbrev E23722 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op y z) y) (op y (op z w))

abbrev E23980 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op (op y z) w) (op u (op u u))

abbrev E24444 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y y) z) (op (op y z) z)

abbrev E24611 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y z) y) (op (op z y) z)

abbrev E25163 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op x (op z y))) (op x w)

abbrev E25165 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op x (op z y))) (op y y)

abbrev E25374 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op z (op x x))) (op x w)

abbrev E25510 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op z (op y w))) (op z y)

abbrev E26018 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op (op x y) z)) (op w w)

abbrev E26318 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op y (op (op z x) w)) (op w u)

abbrev E26522 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op (op z w) y)) (op w z)

abbrev E28035 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op (op y (op z x)) y) (op w u)

abbrev E28075 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op (op y (op z x)) w) (op u z)

abbrev E28363 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op (op y (op z w)) u) (op u z)

abbrev E28976 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op (op y z) y) y) (op x w)

abbrev E29561 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op y (op x (op z (op y w)))) u

abbrev E30386 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op x (op (op y y) z))) z

abbrev E30692 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op z (op (op x w) y))) w

abbrev E31350 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op (op x z) (op w w))) z

abbrev E31429 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op (op y y) (op z w))) y

abbrev E31632 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op (op z y) (op z z))) w

abbrev E31727 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op (op z z) (op w z))) z

abbrev E31842 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op y (op (op z w) (op w u))) w

abbrev E32979 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op (op (op x x) y) z)) y

abbrev E33028 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op (op (op x y) z) z)) y

abbrev E33184 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op (op (op y y) z) w)) z

abbrev E34034 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y y) (op y (op x z))) y

abbrev E34211 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op (op y z) (op x (op w w))) u

abbrev E34242 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op y z) (op y (op y y))) w

abbrev E34267 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op y z) (op y (op z w))) w

abbrev E34317 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y z) (op z (op y y))) y

abbrev E34976 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y y) (op (op z z) x)) y

abbrev E35389 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u v r : α, x = op (op (op y z) (op (op w u) v)) r

abbrev E35840 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y (op y z)) (op y y)) y

abbrev E38508 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op y (op (op y z) w)) y) w

abbrev E39219 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op y x) (op z z)) z) z

abbrev E39222 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op (op y x) (op z z)) w) y

abbrev E39257 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op y y) (op x x)) y) z

abbrev E39681 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op (op (op y z) (op w y)) u) y

abbrev E39753 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op (op (op y z) (op w u)) z) w

abbrev E40148 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op (op y (op y x)) y) z) w

abbrev E40192 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op y (op y y)) z) y) z

abbrev E40300 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op (op y (op z x)) y) x) w







end Luotain.Collapse
