-- Generated by Luotain (https://github.com/anttiluode/Luotain). Core Lean 4, no Mathlib.
set_option maxHeartbeats 1000000
set_option maxRecDepth 100000
set_option linter.unusedVariables false
set_option maxErrors 100000


namespace Luotain.Joins



abbrev E5 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op y x

abbrev E13 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op y (op x x)

abbrev E24 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op x x) y

abbrev E38 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op x y

abbrev E39 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op y x

abbrev E41 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op y z

abbrev E103 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op (op x y) z)

abbrev E238 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op z x)) x

abbrev E242 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op z y)) x

abbrev E256 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op x x) x) y

abbrev E367 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op (op y y) x

abbrev E374 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x y = op (op x x) x

abbrev E3051 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op (op x x) x) x) y

abbrev E3349 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op y (op x (op z y))

abbrev E3744 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op (op x z) (op w y)

abbrev E4274 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op x x) = op y (op x z)

abbrev E4280 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op x x) = op y (op z z)

abbrev E4586 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x x) x = op (op x y) z

abbrev E4589 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x x) x = op (op y x) z

abbrev E4593 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x x) x = op (op y z) x

abbrev E12639 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op x (op (op x (op y (op z w))) u)

abbrev E15156 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op (op (op z w) (op w x)) x)

abbrev E15465 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op (op x (op y x)) z) x)

abbrev E20569 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op x y) (op (op (op x z) w) u)

abbrev E23161 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op x x) y) (op z (op w z))

abbrev E26448 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y (op (op z z) z)) (op w x)

abbrev E26707 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op x y) (op x z)) (op w w)

abbrev E28482 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op (op x y) y) y) (op z w)

abbrev E28638 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op y x) y) z) (op y x)

abbrev E31041 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x (op (op x y) (op z x))) y

abbrev E31079 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x (op (op y x) (op z x))) z

abbrev E33690 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op x y) (op x (op x x))) z

abbrev E34693 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op x y) (op (op z w) x)) w

abbrev E35460 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op x (op y x)) (op y z)) z

abbrev E35801 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y (op y y)) (op z x)) x

abbrev E36461 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op (op x y) z) (op w w)) z

abbrev E36468 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op (op (op x y) z) (op w u)) u

abbrev E36756 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op (op y y) z) (op w z)) x

abbrev E37720 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op (op y (op z (op x w))) u) x

abbrev E38100 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op x (op (op y x) z)) y) w

abbrev E39057 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op (op (op x y) (op z y)) w) u

abbrev E39792 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op x (op x y)) x) x) z

abbrev E39932 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op (op x (op y z)) y) w) z

abbrev E39937 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op x (op y z)) z) x) z

abbrev E41914 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op y (op x (op z (op z w)))

abbrev E42264 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u v : α, op x y = op z (op z (op w (op u v)))

abbrev E42799 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op y (op y (op (op x x) z))

abbrev E43011 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op z (op y (op (op y y) z))

abbrev E43704 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op y (op (op y z) (op z z))

abbrev E43760 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op y (op (op z z) (op w w))

abbrev E43818 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op z (op (op x y) (op w y))

abbrev E44481 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op x (op (op z (op z z)) z)

abbrev E45488 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op y (op (op (op z y) y) z)

abbrev E45737 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op z (op (op (op z z) y) w)

abbrev E46140 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op (op x x) (op z (op x w))

abbrev E46444 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op z x) (op y (op z x))

abbrev E46685 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op x y = op (op z w) (op y (op y u))

abbrev E47002 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op x x) (op (op x z) z)

abbrev E47022 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op x x) (op (op z z) x)

abbrev E47130 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op (op x z) (op (op w z) y)

abbrev E47346 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op x y = op (op z x) (op (op z w) u)

abbrev E48129 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op x y = op (op y (op z y)) (op w u)

abbrev E48154 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op (op y (op z w)) (op y z)

abbrev E48486 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op x y = op (op z (op w w)) (op x u)

abbrev E49299 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op (op (op z w) x) (op w w)

abbrev E49845 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op (op y (op y (op z w))) x

abbrev E50010 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op z (op y (op x y))) z

abbrev E50576 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op x (op (op z x) x)) x

abbrev E50852 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op (op z (op (op x z) w)) z

abbrev E51160 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op x y = op (op z (op (op w u) w)) w

abbrev E52432 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op (op y (op x z)) y) y

abbrev E53025 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op (op (op y y) x) z) x

abbrev E54304 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op y y) = op z (op w (op w w))

abbrev E54598 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op y z) = op w (op z (op x w))

abbrev E55277 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op y z) = op y (op (op x z) w)

abbrev E60497 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op (op x y) z = op (op x z) (op w x)

abbrev E61431 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x y) z = op (op y (op y z)) y

abbrev E61623 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op (op x y) z = op (op w (op z z)) z

abbrev E61660 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op (op x y) z = op (op w (op w u)) w

abbrev E62538 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op (op x y) z = op (op (op w w) u) u





theorem imp_4593_61623 : ∀ (α : Type) (op : α → α → α), E4593 op → E61623 op := by
  intro α op h
  unfold E4593 at h
  unfold E61623
  intro x y z w
  grind

theorem imp_61431_4589 : ∀ (α : Type) (op : α → α → α), E61431 op → E4589 op := by
  intro α op h
  unfold E61431 at h
  unfold E4589
  intro x y z
  have s0 : ∀ v2 v0 v1 : α, (op (op v0 v1) v2) = (op (op v1 (op v1 v2)) v1) := by intros; grind
  have s1 : (op x x) = (op x x) := by grind
  have s2 : (op (op x x) x) = (op (op x x) x) := by grind
  have s3 : (op y x) = (op y x) := by grind
  have s4 : (op (op y x) z) = (op (op y x) z) := by grind
  have s5 : ∀ v0 : α, (op (op v0 x) x) = (op (op x (op x x)) x) := by intros; grind
  have s6 : ∀ v0 : α, (op (op v0 (op x x)) x) = (op (op (op x x) (op (op x x) x)) (op x x)) := by intros; grind
  have s7 : (op (op x (op x x)) x) = (op (op (op x x) x) x) := by grind
  have s8 : ∀ v0 : α, (op (op x (op x x)) x) = (op (op (op v0 (op v0 x)) v0) x) := by intros; grind
  have s9 : ∀ v0 : α, (op (op x (op x x)) x) = (op (op v0 (op v0 x)) v0) := by intros; grind
  have s10 : ∀ v0 : α, (op (op (op x x) x) x) = (op (op v0 (op v0 x)) v0) := by intros; grind
  have s11 : ∀ v0 : α, (op (op v0 x) x) = (op (op (op x x) x) x) := by intros; grind
  have s12 : (op (op x x) x) = (op (op (op x x) x) x) := by grind
  have s13 : (op (op x x) x) = (op (op (op x x) x) x) := by grind
  have s14 : ∀ v0 : α, (op (op v0 (op x x)) x) = (op (op (op v0 (op x x)) x) x) := by intros; grind
  have s15 : ∀ v0 : α, (op (op x (op x x)) x) = (op (op v0 (op x x)) x) := by intros; grind
  have s16 : ∀ v0 : α, (op (op v0 (op x x)) x) = (op (op (op x x) x) x) := by intros; grind
  have s17 : ∀ v0 : α, (op (op x x) x) = (op (op v0 (op x x)) x) := by intros; grind
  have s18 : ∀ v0 : α, (op (op x x) x) = (op (op (op v0 (op v0 (op x x))) v0) x) := by intros; grind
  have s19 : ∀ v0 : α, (op (op x x) x) = (op (op v0 (op v0 x)) v0) := by intros; grind
  have s20 : ∀ v0 v1 : α, (op (op x x) x) = (op (op v0 v1) x) := by intros; grind
  have s21 : ∀ v0 v1 : α, (op (op x x) x) = (op (op v0 x) v1) := by intros; grind
  have s22 : ∀ v0 : α, (op (op x x) x) = (op (op y x) v0) := by intros; grind
  have s23 : (op (op x x) x) = (op (op y x) z) := by grind
  grind

theorem imp_4589_61431 : ∀ (α : Type) (op : α → α → α), E4589 op → E61431 op := by
  intro α op h
  unfold E4589 at h
  unfold E61431
  intro x y z
  grind

theorem imp_374_46140 : ∀ (α : Type) (op : α → α → α), E374 op → E46140 op := by
  intro α op h
  unfold E374 at h
  unfold E46140
  intro x y z w
  grind

theorem imp_41_42799 : ∀ (α : Type) (op : α → α → α), E41 op → E42799 op := by
  intro α op h
  unfold E41 at h
  unfold E42799
  intro x y z
  grind

theorem imp_39_52432 : ∀ (α : Type) (op : α → α → α), E39 op → E52432 op := by
  intro α op h
  unfold E39 at h
  unfold E52432
  intro x y z
  grind

theorem imp_47130_3744 : ∀ (α : Type) (op : α → α → α), E47130 op → E3744 op := by
  intro α op h
  unfold E47130 at h
  unfold E3744
  intro x y z w
  grind

theorem imp_3744_47130 : ∀ (α : Type) (op : α → α → α), E3744 op → E47130 op := by
  intro α op h
  unfold E3744 at h
  unfold E47130
  intro x y z w
  grind

theorem imp_62538_4589 : ∀ (α : Type) (op : α → α → α), E62538 op → E4589 op := by
  intro α op h
  unfold E62538 at h
  unfold E4589
  intro x y z
  grind

theorem imp_44481_38 : ∀ (α : Type) (op : α → α → α), E44481 op → E38 op := by
  intro α op h
  unfold E44481 at h
  unfold E38
  intro x y
  grind

theorem imp_38_44481 : ∀ (α : Type) (op : α → α → α), E38 op → E44481 op := by
  intro α op h
  unfold E38 at h
  unfold E44481
  intro x y z
  grind

theorem imp_41_43704 : ∀ (α : Type) (op : α → α → α), E41 op → E43704 op := by
  intro α op h
  unfold E41 at h
  unfold E43704
  intro x y z
  grind

theorem imp_50576_374 : ∀ (α : Type) (op : α → α → α), E50576 op → E374 op := by
  intro α op h
  unfold E50576 at h
  unfold E374
  intro x y
  grind

theorem imp_374_50576 : ∀ (α : Type) (op : α → α → α), E374 op → E50576 op := by
  intro α op h
  unfold E374 at h
  unfold E50576
  intro x y z
  grind

theorem imp_48154_41 : ∀ (α : Type) (op : α → α → α), E48154 op → E41 op := by
  intro α op h
  unfold E48154 at h
  unfold E41
  intro x y z
  grind

theorem imp_238_35801 : ∀ (α : Type) (op : α → α → α), E238 op → E35801 op := by
  intro α op h
  unfold E238 at h
  unfold E35801
  intro x y z
  grind

theorem imp_4274_55277 : ∀ (α : Type) (op : α → α → α), E4274 op → E55277 op := by
  intro α op h
  unfold E4274 at h
  unfold E55277
  intro x y z w
  grind

theorem imp_41_48486 : ∀ (α : Type) (op : α → α → α), E41 op → E48486 op := by
  intro α op h
  unfold E41 at h
  unfold E48486
  intro x y z w u
  grind

theorem imp_41_45737 : ∀ (α : Type) (op : α → α → α), E41 op → E45737 op := by
  intro α op h
  unfold E41 at h
  unfold E45737
  intro x y z w
  grind

theorem imp_103_12639 : ∀ (α : Type) (op : α → α → α), E103 op → E12639 op := by
  intro α op h
  unfold E103 at h
  unfold E12639
  intro x y z w u
  grind

theorem imp_5_37720 : ∀ (α : Type) (op : α → α → α), E5 op → E37720 op := by
  intro α op h
  unfold E5 at h
  unfold E37720
  intro x y z w u
  grind

theorem imp_47002_374 : ∀ (α : Type) (op : α → α → α), E47002 op → E374 op := by
  intro α op h
  unfold E47002 at h
  unfold E374
  intro x y
  grind

theorem imp_374_47002 : ∀ (α : Type) (op : α → α → α), E374 op → E47002 op := by
  intro α op h
  unfold E374 at h
  unfold E47002
  intro x y z
  grind

theorem imp_41_43760 : ∀ (α : Type) (op : α → α → α), E41 op → E43760 op := by
  intro α op h
  unfold E41 at h
  unfold E43760
  intro x y z w
  grind

theorem imp_60497_4586 : ∀ (α : Type) (op : α → α → α), E60497 op → E4586 op := by
  intro α op h
  unfold E60497 at h
  unfold E4586
  intro x y z
  grind

theorem imp_4586_60497 : ∀ (α : Type) (op : α → α → α), E4586 op → E60497 op := by
  intro α op h
  unfold E4586 at h
  unfold E60497
  intro x y z w
  grind

theorem imp_41914_41 : ∀ (α : Type) (op : α → α → α), E41914 op → E41 op := by
  intro α op h
  unfold E41914 at h
  unfold E41
  intro x y z
  grind

theorem imp_54598_4274 : ∀ (α : Type) (op : α → α → α), E54598 op → E4274 op := by
  intro α op h
  unfold E54598 at h
  unfold E4274
  intro x y z
  grind

theorem imp_367_53025 : ∀ (α : Type) (op : α → α → α), E367 op → E53025 op := by
  intro α op h
  unfold E367 at h
  unfold E53025
  intro x y z
  grind

theorem imp_46444_41 : ∀ (α : Type) (op : α → α → α), E46444 op → E41 op := by
  intro α op h
  unfold E46444 at h
  unfold E41
  intro x y z
  have s0 : ∀ v2 v0 v1 : α, (op v0 v1) = (op (op v2 v0) (op v1 (op v2 v0))) := by intros; grind
  have s1 : (op x x) = (op x x) := by grind
  have s2 : (op y z) = (op y z) := by grind
  have s3 : ∀ v0 : α, (op x v0) = (op (op x x) (op v0 (op x x))) := by intros; grind
  have s4 : ∀ v0 : α, (op z v0) = (op (op y z) (op v0 (op y z))) := by intros; grind
  have s5 : ∀ v0 v1 : α, (op (op v0 (op x x)) v1) = (op (op x v0) (op v1 (op x v0))) := by intros; grind
  have s6 : ∀ v0 v1 : α, (op v0 v1) = (op (op v0 (op x x)) v1) := by intros; grind
  have s7 : ∀ v0 : α, (op (op y z) (op y z)) = (op (op v0 (op y z)) (op z v0)) := by intros; grind
  have s8 : ∀ v0 v1 : α, (op (op v0 (op y z)) v1) = (op (op z v0) (op v1 (op z v0))) := by intros; grind
  have s9 : ∀ v0 v1 : α, (op v0 v1) = (op (op v0 (op y z)) v1) := by intros; grind
  have s10 : ∀ v2 v0 v1 : α, (op v2 (op v0 (op x x))) = (op (op v1 v2) (op v0 (op v1 v2))) := by intros; grind
  have s11 : ∀ v2 v0 : α, (op v2 v0) = (op v2 (op v0 (op x x))) := by intros; grind
  have s12 : ∀ v2 v0 v1 : α, (op (op v1 v2) (op v0 (op v1 v2))) = (op v2 (op v0 (op y z))) := by intros; grind
  have s13 : ∀ v0 : α, (op (op x x) (op v0 (op x x))) = (op x (op v0 (op y z))) := by intros; grind
  have s14 : ∀ v0 : α, (op (op y z) (op v0 (op y z))) = (op z (op v0 (op y z))) := by intros; grind
  have s15 : ∀ v0 : α, (op z v0) = (op z (op v0 (op y z))) := by intros; grind
  have s16 : ∀ v0 : α, (op x v0) = (op x (op v0 (op y z))) := by intros; grind
  have s17 : ∀ v2 v0 : α, (op v2 v0) = (op v2 (op v0 (op y z))) := by intros; grind
  have s18 : ∀ v0 v1 : α, (op (op x x) v0) = (op (op v1 (op x x)) (op v0 v1)) := by intros; grind
  have s19 : ∀ v0 : α, (op x v0) = (op (op x x) v0) := by intros; grind
  have s20 : ∀ v0 v1 : α, (op (op x x) v0) = (op v1 (op v0 v1)) := by intros; grind
  have s21 : ∀ v0 v1 : α, (op x v0) = (op v1 (op v0 v1)) := by intros; grind
  have s22 : ∀ v0 : α, (op (op v0 (op y z)) (op z v0)) = (op (op y z) z) := by intros; grind
  have s23 : (op (op y z) (op y z)) = (op (op y z) z) := by grind
  have s24 : ∀ v0 : α, (op z v0) = (op (op (op y z) (op y z)) (op v0 (op (op y z) (op y z)))) := by intros; grind
  have s25 : ∀ v0 : α, (op z v0) = (op (op y z) v0) := by intros; grind
  have s26 : ∀ v0 : α, (op v0 z) = (op v0 (op (op y z) (op x x))) := by intros; grind
  have s27 : ∀ v0 : α, (op v0 (op y z)) = (op v0 z) := by intros; grind
  have s28 : (op y z) = (op y (op y z)) := by grind
  have s29 : ∀ v0 : α, (op (op y z) v0) = (op y v0) := by intros; grind
  have s30 : (op y z) = (op (op y z) (op y z)) := by grind
  have s31 : ∀ v0 v1 : α, (op (op y z) v0) = (op (op v1 (op y z)) (op v0 v1)) := by intros; grind
  have s32 : ∀ v0 v1 : α, (op (op y z) v0) = (op v1 (op v0 v1)) := by intros; grind
  have s33 : ∀ v0 : α, (op x v0) = (op (op y z) v0) := by intros; grind
  have s34 : (op y z) = (op x (op y z)) := by grind
  have s35 : (op x (op y z)) = (op x (op x (op y z))) := by grind
  have s36 : (op x x) = (op x (op y z)) := by grind
  have s37 : (op x x) = (op y z) := by grind
  have s38 : (op x x) = (op y z) := by grind
  grind

theorem imp_3349_43818 : ∀ (α : Type) (op : α → α → α), E3349 op → E43818 op := by
  intro α op h
  unfold E3349 at h
  unfold E43818
  intro x y z w
  grind

theorem imp_49299_41 : ∀ (α : Type) (op : α → α → α), E49299 op → E41 op := by
  intro α op h
  unfold E49299 at h
  unfold E41
  intro x y z
  grind

theorem imp_41_49299 : ∀ (α : Type) (op : α → α → α), E41 op → E49299 op := by
  intro α op h
  unfold E41 at h
  unfold E49299
  intro x y z w
  grind

theorem imp_41_43011 : ∀ (α : Type) (op : α → α → α), E41 op → E43011 op := by
  intro α op h
  unfold E41 at h
  unfold E43011
  intro x y z
  grind

theorem imp_61660_4589 : ∀ (α : Type) (op : α → α → α), E61660 op → E4589 op := by
  intro α op h
  unfold E61660 at h
  unfold E4589
  intro x y z
  grind

theorem imp_47022_374 : ∀ (α : Type) (op : α → α → α), E47022 op → E374 op := by
  intro α op h
  unfold E47022 at h
  unfold E374
  intro x y
  grind

theorem imp_374_47022 : ∀ (α : Type) (op : α → α → α), E374 op → E47022 op := by
  intro α op h
  unfold E374 at h
  unfold E47022
  intro x y z
  grind

theorem imp_45488_41 : ∀ (α : Type) (op : α → α → α), E45488 op → E41 op := by
  intro α op h
  unfold E45488 at h
  unfold E41
  intro x y z
  have s0 : ∀ v2 v0 v1 : α, (op v0 v1) = (op v1 (op (op (op v2 v1) v1) v2)) := by intros; grind
  have s1 : (op x x) = (op x x) := by grind
  have s2 : (op y z) = (op y z) := by grind
  have s3 : ∀ v2 v0 v1 : α, (op v0 v1) = (op v2 v1) := by intros; grind
  have s4 : ∀ v0 : α, (op x x) = (op v0 x) := by intros; grind
  have s5 : ∀ v0 : α, (op y z) = (op v0 z) := by intros; grind
  have s6 : ∀ v0 v1 : α, (op v0 v1) = (op v1 (op x x)) := by intros; grind
  have s7 : (op x x) = (op x (op x x)) := by grind
  have s8 : (op y z) = (op z (op x x)) := by grind
  have s9 : (op y z) = (op (op x x) (op x x)) := by grind
  have s10 : ∀ v0 : α, (op x x) = (op v0 (op x x)) := by intros; grind
  have s11 : ∀ v0 : α, (op y z) = (op v0 (op x x)) := by intros; grind
  have s12 : (op x x) = (op y z) := by grind
  grind



end Luotain.Joins
