-- Generated by Luotain (https://github.com/anttiluode/Luotain). Core Lean 4, no Mathlib.
set_option maxHeartbeats 1000000
set_option maxRecDepth 100000
set_option linter.unusedVariables false
set_option maxErrors 100000


namespace Luotain.NewLaws



abbrev E64 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op x (op x z))

abbrev E114 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op y (op (op x x) x)

abbrev E126 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op y x) z)

abbrev E212 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op x (op y y)) y

abbrev E258 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op x x) y) y

abbrev E326 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x y = op x (op y y)

abbrev E343 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op z (op x y)

abbrev E488 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op x (op z (op y y)))

abbrev E622 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op x (op x (op (op y y) x))

abbrev E676 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op y (op x (op (op y x) x))

abbrev E691 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op x (op (op z y) y))

abbrev E764 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op z (op (op y y) w))

abbrev E935 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op y z) (op z y))

abbrev E995 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op (op z w) (op x y))

abbrev E1022 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op x (op (op x (op x y)) x)

abbrev E1029 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op x (op (op x (op y y)) y)

abbrev E1089 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op x (op y z)) y)

abbrev E1224 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op x (op (op (op x x) x) y)

abbrev E1240 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op (op (op y x) x) z)

abbrev E1299 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op (op x z) y) x)

abbrev E1322 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op y (op (op (op y y) x) x)

abbrev E1553 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y z) (op x (op x y))

abbrev E1555 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y z) (op x (op x w))

abbrev E1680 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op x y) (op (op z w) u)

abbrev E1688 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y x) (op (op x z) y)

abbrev E1763 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y z) (op (op x z) x)

abbrev E1792 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y z) (op (op z x) w)

abbrev E1801 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y z) (op (op z w) x)

abbrev E1818 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op y z) (op (op w z) z)

abbrev E1857 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op x (op y y)) (op x x)

abbrev E1881 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op x (op y z)) (op w z)

abbrev E2112 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y x) z) (op y y)

abbrev E2209 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op y z) z) (op w z)

abbrev E2333 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op y (op x z))) x

abbrev E2389 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op z (op y z))) x

abbrev E2753 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y y) (op z x)) x

abbrev E2788 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y z) (op y x)) y

abbrev E2812 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y z) (op z z)) x

abbrev E2863 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op x (op y x)) x) y

abbrev E3152 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op (op y y) y) y) x

abbrev E3193 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op y z) y) x) x

abbrev E3583 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op z (op (op x x) y)

abbrev E3584 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op z (op (op x x) z)

abbrev E3602 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op z (op (op y x) w)

abbrev E3715 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x y = op (op x x) (op y y)

abbrev E3768 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op y z) (op x x)

abbrev E3860 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op x y = op (op z w) (op u u)

abbrev E3864 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op (op x (op x y)) x

abbrev E3981 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op y (op z z)) z

abbrev E4009 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op z (op y y)) x

abbrev E4071 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op (op (op x y) x) y

abbrev E4203 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op (op (op z x) w) x

abbrev E4234 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op (op z z) z) y

abbrev E4402 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op x y) = op (op x z) y

abbrev E4429 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op x y) = op (op z w) z

abbrev E4438 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y x) = op (op x z) x

abbrev E4492 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op y y) = op (op z x) w

abbrev E4614 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x x) y = op (op z x) x

abbrev E5498 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op y (op z (op w (op z (op w x))))

abbrev E5665 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op x (op y (op y (op (op x y) y)))

abbrev E6467 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op x (op x (op (op y x) (op y x)))

abbrev E6981 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op z (op (op x y) (op z z)))

abbrev E8746 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op z (op (op (op x z) y) x))

abbrev E15036 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op (op z z) (op z x)) y)

abbrev E16780 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op (op (op z z) y) z) x)

abbrev E17045 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x y) (op x (op z (op x x)))

abbrev E17196 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y x) (op x (op z (op x x)))

abbrev E19082 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op y y) (op (op x x) (op x y))

abbrev E19611 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x x) (op (op x (op y x)) z)

abbrev E19676 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x y) (op (op x (op z x)) x)

abbrev E20485 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x x) (op (op (op x x) y) z)

abbrev E21379 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x (op x y)) (op x (op z x))

abbrev E21411 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op x (op y x)) (op x (op x y))

abbrev E24088 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op x y) y) (op (op y x) x)

abbrev E28442 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op x y) x) y) (op z x)

abbrev E29495 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op y (op x (op y (op x y)))) y

abbrev E30523 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op y (op y (op (op y x) y))) y

abbrev E33706 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op x y) (op x (op y z))) z

abbrev E35640 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op y (op x y)) (op y x)) x

abbrev E36393 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op x y) z) (op x x)) x

abbrev E41680 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op y (op z (op y (op z x)))

abbrev E42178 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op z (op y (op w (op w y)))

abbrev E43006 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op z (op y (op (op y x) y))

abbrev E43320 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op x (op (op y z) (op x z))

abbrev E44185 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op x (op (op y (op y x)) x)

abbrev E45078 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op x (op (op (op y z) y) z)

abbrev E45501 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op y (op (op (op z z) x) z)

abbrev E45661 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op z (op (op (op y z) z) x)

abbrev E46836 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op x y) (op (op z z) z)

abbrev E49494 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op y (op x (op z x))) x

abbrev E51193 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op (op x y) (op x x)) z

abbrev E51340 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op (op y z) (op z y)) x

abbrev E51433 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op (op x y) (op y z)) y

abbrev E51854 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op (op z z) (op y x)) z

abbrev E52112 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op (op y (op x x)) z) y

abbrev E53003 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op (op (op y x) z) x) y

abbrev E53822 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x (op x x) = op y (op x (op x x))

abbrev E54041 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op y x) = op x (op z (op z w))

abbrev E54106 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y x) = op z (op y (op y y))

abbrev E54167 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y y) = op x (op x (op z x))

abbrev E54550 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op y z) = op w (op x (op y z))

abbrev E54956 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op y x) = op y (op (op z w) x)

abbrev E55824 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op y x) = op (op y z) (op x w)

abbrev E56522 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op x y) = op (op x (op z w)) x

abbrev E56799 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y y) = op (op x (op x z)) y

abbrev E56870 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y y) = op (op z (op x y)) x

abbrev E57191 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op y z) = op (op w (op x w)) z

abbrev E57749 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y y) = op (op (op z x) y) z

abbrev E58261 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x x) y = op x (op y (op z y))

abbrev E59558 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op (op x y) y = op z (op (op w z) x)

abbrev E59673 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x y) z = op y (op (op y y) y)

abbrev E60021 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op (op x x) y = op (op x z) (op x w)

abbrev E60167 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x y) x = op (op x y) (op z z)

abbrev E60177 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x y) x = op (op x z) (op z x)

abbrev E60946 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op (op x x) y = op (op y (op z w)) z

abbrev E60961 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op (op x x) y = op (op z (op x w)) x

abbrev E61112 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op (op x y) x = op (op z (op x w)) x

abbrev E62056 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x y) y = op (op (op x x) x) z



def P0_tbl : List Nat := [0, 1, 2, 1, 2, 0, 2, 0, 1]
def P0 (a b : Fin 3) : Fin 3 := ⟨(P0_tbl.getD (3 * a.val + b.val) 0) % 3, Nat.mod_lt _ (by decide)⟩

def P1_tbl : List Nat := [0, 0, 0, 0]
def P1 (a b : Fin 2) : Fin 2 := ⟨(P1_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P2_tbl : List Nat := [0, 0, 1, 0]
def P2 (a b : Fin 2) : Fin 2 := ⟨(P2_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P3_tbl : List Nat := [0, 1, 0, 0]
def P3 (a b : Fin 2) : Fin 2 := ⟨(P3_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P4_tbl : List Nat := [0, 0, 1, 1]
def P4 (a b : Fin 2) : Fin 2 := ⟨(P4_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P5_tbl : List Nat := [1, 0, 1, 0]
def P5 (a b : Fin 2) : Fin 2 := ⟨(P5_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P6_tbl : List Nat := [1, 0, 0, 0]
def P6 (a b : Fin 2) : Fin 2 := ⟨(P6_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P7_tbl : List Nat := [0, 1, 0, 1]
def P7 (a b : Fin 2) : Fin 2 := ⟨(P7_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P8_tbl : List Nat := [0, 1, 2, 3, 4, 1, 2, 3, 4, 0, 2, 3, 4, 0, 1, 3, 4, 0, 1, 2, 4, 0, 1, 2, 3]
def P8 (a b : Fin 5) : Fin 5 := ⟨(P8_tbl.getD (5 * a.val + b.val) 0) % 5, Nat.mod_lt _ (by decide)⟩

def P9_tbl : List Nat := [1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0]
def P9 (a b : Fin 5) : Fin 5 := ⟨(P9_tbl.getD (5 * a.val + b.val) 0) % 5, Nat.mod_lt _ (by decide)⟩

def P10_tbl : List Nat := [0, 2, 1, 2, 1, 0, 1, 0, 2]
def P10 (a b : Fin 3) : Fin 3 := ⟨(P10_tbl.getD (3 * a.val + b.val) 0) % 3, Nat.mod_lt _ (by decide)⟩

def P11_tbl : List Nat := [0, 0, 1, 0, 0, 0, 0, 0, 0]
def P11 (a b : Fin 3) : Fin 3 := ⟨(P11_tbl.getD (3 * a.val + b.val) 0) % 3, Nat.mod_lt _ (by decide)⟩

def P12_tbl : List Nat := [0, 3, 1, 4, 2, 3, 1, 4, 2, 0, 1, 4, 2, 0, 3, 4, 2, 0, 3, 1, 2, 0, 3, 1, 4]
def P12 (a b : Fin 5) : Fin 5 := ⟨(P12_tbl.getD (5 * a.val + b.val) 0) % 5, Nat.mod_lt _ (by decide)⟩

def P13_tbl : List Nat := [0, 0, 0, 0, 0, 1, 0, 0, 1]
def P13 (a b : Fin 3) : Fin 3 := ⟨(P13_tbl.getD (3 * a.val + b.val) 0) % 3, Nat.mod_lt _ (by decide)⟩

def P14_tbl : List Nat := [1, 1, 0, 0]
def P14 (a b : Fin 2) : Fin 2 := ⟨(P14_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P15_tbl : List Nat := [0, 0, 0, 0, 0, 0, 0, 0, 1]
def P15 (a b : Fin 3) : Fin 3 := ⟨(P15_tbl.getD (3 * a.val + b.val) 0) % 3, Nat.mod_lt _ (by decide)⟩



theorem not_45501_3602 : ¬ ∀ (α : Type) (op : α → α → α), E45501 op → E3602 op := by
  intro h
  have hb : ¬ E3602 P0 := by unfold E3602; decide
  exact hb (h (Fin 3) P0 (by unfold E45501; decide))

theorem not_60167_1322 : ¬ ∀ (α : Type) (op : α → α → α), E60167 op → E1322 op := by
  intro h
  have hb : ¬ E1322 P1 := by unfold E1322; decide
  exact hb (h (Fin 2) P1 (by unfold E60167; decide))

theorem not_53822_2788 : ¬ ∀ (α : Type) (op : α → α → α), E53822 op → E2788 op := by
  intro h
  have hb : ¬ E2788 P1 := by unfold E2788; decide
  exact hb (h (Fin 2) P1 (by unfold E53822; decide))

theorem not_52112_3768 : ¬ ∀ (α : Type) (op : α → α → α), E52112 op → E3768 op := by
  intro h
  have hb : ¬ E3768 P2 := by unfold E3768; decide
  exact hb (h (Fin 2) P2 (by unfold E52112; decide))

theorem not_56799_1857 : ¬ ∀ (α : Type) (op : α → α → α), E56799 op → E1857 op := by
  intro h
  have hb : ¬ E1857 P1 := by unfold E1857; decide
  exact hb (h (Fin 2) P1 (by unfold E56799; decide))

theorem not_56522_258 : ¬ ∀ (α : Type) (op : α → α → α), E56522 op → E258 op := by
  intro h
  have hb : ¬ E258 P1 := by unfold E258; decide
  exact hb (h (Fin 2) P1 (by unfold E56522; decide))

theorem not_36393_1022 : ¬ ∀ (α : Type) (op : α → α → α), E36393 op → E1022 op := by
  intro h
  have hb : ¬ E1022 P3 := by unfold E1022; decide
  exact hb (h (Fin 2) P3 (by unfold E36393; decide))

theorem not_28442_4234 : ¬ ∀ (α : Type) (op : α → α → α), E28442 op → E4234 op := by
  intro h
  have hb : ¬ E4234 P4 := by unfold E4234; decide
  exact hb (h (Fin 2) P4 (by unfold E28442; decide))

theorem not_43006_343 : ¬ ∀ (α : Type) (op : α → α → α), E43006 op → E343 op := by
  intro h
  have hb : ¬ E343 P5 := by unfold E343; decide
  exact hb (h (Fin 2) P5 (by unfold E43006; decide))

theorem not_45661_326 : ¬ ∀ (α : Type) (op : α → α → α), E45661 op → E326 op := by
  intro h
  have hb : ¬ E326 P0 := by unfold E326; decide
  exact hb (h (Fin 3) P0 (by unfold E45661; decide))

theorem not_17196_1801 : ¬ ∀ (α : Type) (op : α → α → α), E17196 op → E1801 op := by
  intro h
  have hb : ¬ E1801 P6 := by unfold E1801; decide
  exact hb (h (Fin 2) P6 (by unfold E17196; decide))

theorem not_43320_1089 : ¬ ∀ (α : Type) (op : α → α → α), E43320 op → E1089 op := by
  intro h
  have hb : ¬ E1089 P1 := by unfold E1089; decide
  exact hb (h (Fin 2) P1 (by unfold E43320; decide))

theorem not_53003_2333 : ¬ ∀ (α : Type) (op : α → α → α), E53003 op → E2333 op := by
  intro h
  have hb : ¬ E2333 P1 := by unfold E2333; decide
  exact hb (h (Fin 2) P1 (by unfold E53003; decide))

theorem not_16780_3860 : ¬ ∀ (α : Type) (op : α → α → α), E16780 op → E3860 op := by
  intro h
  have hb : ¬ E3860 P7 := by unfold E3860; decide
  exact hb (h (Fin 2) P7 (by unfold E16780; decide))

theorem not_17045_1688 : ¬ ∀ (α : Type) (op : α → α → α), E17045 op → E1688 op := by
  intro h
  have hb : ¬ E1688 P4 := by unfold E1688; decide
  exact hb (h (Fin 2) P4 (by unfold E17045; decide))

theorem not_20485_4429 : ¬ ∀ (α : Type) (op : α → α → α), E20485 op → E4429 op := by
  intro h
  have hb : ¬ E4429 P4 := by unfold E4429; decide
  exact hb (h (Fin 2) P4 (by unfold E20485; decide))

theorem not_30523_4071 : ¬ ∀ (α : Type) (op : α → α → α), E30523 op → E4071 op := by
  intro h
  have hb : ¬ E4071 P8 := by unfold E4071; decide
  exact hb (h (Fin 5) P8 (by unfold E30523; decide))

theorem not_61112_1029 : ¬ ∀ (α : Type) (op : α → α → α), E61112 op → E1029 op := by
  intro h
  have hb : ¬ E1029 P1 := by unfold E1029; decide
  exact hb (h (Fin 2) P1 (by unfold E61112; decide))

theorem not_6467_64 : ¬ ∀ (α : Type) (op : α → α → α), E6467 op → E64 op := by
  intro h
  have hb : ¬ E64 P4 := by unfold E64; decide
  exact hb (h (Fin 2) P4 (by unfold E6467; decide))

theorem not_21379_1881 : ¬ ∀ (α : Type) (op : α → α → α), E21379 op → E1881 op := by
  intro h
  have hb : ¬ E1881 P7 := by unfold E1881; decide
  exact hb (h (Fin 2) P7 (by unfold E21379; decide))

theorem not_19676_4492 : ¬ ∀ (α : Type) (op : α → α → α), E19676 op → E4492 op := by
  intro h
  have hb : ¬ E4492 P4 := by unfold E4492; decide
  exact hb (h (Fin 2) P4 (by unfold E19676; decide))

theorem not_45078_3981 : ¬ ∀ (α : Type) (op : α → α → α), E45078 op → E3981 op := by
  intro h
  have hb : ¬ E3981 P4 := by unfold E3981; decide
  exact hb (h (Fin 2) P4 (by unfold E45078; decide))

theorem not_5498_622 : ¬ ∀ (α : Type) (op : α → α → α), E5498 op → E622 op := by
  intro h
  have hb : ¬ E622 P9 := by unfold E622; decide
  exact hb (h (Fin 5) P9 (by unfold E5498; decide))

theorem not_44185_764 : ¬ ∀ (α : Type) (op : α → α → α), E44185 op → E764 op := by
  intro h
  have hb : ¬ E764 P1 := by unfold E764; decide
  exact hb (h (Fin 2) P1 (by unfold E44185; decide))

theorem not_19611_114 : ¬ ∀ (α : Type) (op : α → α → α), E19611 op → E114 op := by
  intro h
  have hb : ¬ E114 P4 := by unfold E114; decide
  exact hb (h (Fin 2) P4 (by unfold E19611; decide))

theorem not_29495_3584 : ¬ ∀ (α : Type) (op : α → α → α), E29495 op → E3584 op := by
  intro h
  have hb : ¬ E3584 P10 := by unfold E3584; decide
  exact hb (h (Fin 3) P10 (by unfold E29495; decide))

theorem not_57191_2389 : ¬ ∀ (α : Type) (op : α → α → α), E57191 op → E2389 op := by
  intro h
  have hb : ¬ E2389 P1 := by unfold E2389; decide
  exact hb (h (Fin 2) P1 (by unfold E57191; decide))

theorem not_21411_2112 : ¬ ∀ (α : Type) (op : α → α → α), E21411 op → E2112 op := by
  intro h
  have hb : ¬ E2112 P4 := by unfold E2112; decide
  exact hb (h (Fin 2) P4 (by unfold E21411; decide))

theorem not_51854_691 : ¬ ∀ (α : Type) (op : α → α → α), E51854 op → E691 op := by
  intro h
  have hb : ¬ E691 P1 := by unfold E691; decide
  exact hb (h (Fin 2) P1 (by unfold E51854; decide))

theorem not_41680_3864 : ¬ ∀ (α : Type) (op : α → α → α), E41680 op → E3864 op := by
  intro h
  have hb : ¬ E3864 P11 := by unfold E3864; decide
  exact hb (h (Fin 3) P11 (by unfold E41680; decide))

theorem not_42178_2209 : ¬ ∀ (α : Type) (op : α → α → α), E42178 op → E2209 op := by
  intro h
  have hb : ¬ E2209 P1 := by unfold E2209; decide
  exact hb (h (Fin 2) P1 (by unfold E42178; decide))

theorem not_57749_3152 : ¬ ∀ (α : Type) (op : α → α → α), E57749 op → E3152 op := by
  intro h
  have hb : ¬ E3152 P1 := by unfold E3152; decide
  exact hb (h (Fin 2) P1 (by unfold E57749; decide))

theorem not_19082_2863 : ¬ ∀ (α : Type) (op : α → α → α), E19082 op → E2863 op := by
  intro h
  have hb : ¬ E2863 P12 := by unfold E2863; decide
  exact hb (h (Fin 5) P12 (by unfold E19082; decide))

theorem not_60177_995 : ¬ ∀ (α : Type) (op : α → α → α), E60177 op → E995 op := by
  intro h
  have hb : ¬ E995 P1 := by unfold E995; decide
  exact hb (h (Fin 2) P1 (by unfold E60177; decide))

theorem not_59673_2753 : ¬ ∀ (α : Type) (op : α → α → α), E59673 op → E2753 op := by
  intro h
  have hb : ¬ E2753 P1 := by unfold E2753; decide
  exact hb (h (Fin 2) P1 (by unfold E59673; decide))

theorem not_54167_1555 : ¬ ∀ (α : Type) (op : α → α → α), E54167 op → E1555 op := by
  intro h
  have hb : ¬ E1555 P1 := by unfold E1555; decide
  exact hb (h (Fin 2) P1 (by unfold E54167; decide))

theorem not_8746_126 : ¬ ∀ (α : Type) (op : α → α → α), E8746 op → E126 op := by
  intro h
  have hb : ¬ E126 P7 := by unfold E126; decide
  exact hb (h (Fin 2) P7 (by unfold E8746; decide))

theorem not_54041_4614 : ¬ ∀ (α : Type) (op : α → α → α), E54041 op → E4614 op := by
  intro h
  have hb : ¬ E4614 P4 := by unfold E4614; decide
  exact hb (h (Fin 2) P4 (by unfold E54041; decide))

theorem not_51193_1680 : ¬ ∀ (α : Type) (op : α → α → α), E51193 op → E1680 op := by
  intro h
  have hb : ¬ E1680 P1 := by unfold E1680; decide
  exact hb (h (Fin 2) P1 (by unfold E51193; decide))

theorem not_56870_4438 : ¬ ∀ (α : Type) (op : α → α → α), E56870 op → E4438 op := by
  intro h
  have hb : ¬ E4438 P13 := by unfold E4438; decide
  exact hb (h (Fin 3) P13 (by unfold E56870; decide))

theorem not_24088_488 : ¬ ∀ (α : Type) (op : α → α → α), E24088 op → E488 op := by
  intro h
  have hb : ¬ E488 P4 := by unfold E488; decide
  exact hb (h (Fin 2) P4 (by unfold E24088; decide))

theorem not_60961_212 : ¬ ∀ (α : Type) (op : α → α → α), E60961 op → E212 op := by
  intro h
  have hb : ¬ E212 P1 := by unfold E212; decide
  exact hb (h (Fin 2) P1 (by unfold E60961; decide))

theorem not_59558_676 : ¬ ∀ (α : Type) (op : α → α → α), E59558 op → E676 op := by
  intro h
  have hb : ¬ E676 P1 := by unfold E676; decide
  exact hb (h (Fin 2) P1 (by unfold E59558; decide))

theorem not_15036_1299 : ¬ ∀ (α : Type) (op : α → α → α), E15036 op → E1299 op := by
  intro h
  have hb : ¬ E1299 P10 := by unfold E1299; decide
  exact hb (h (Fin 3) P10 (by unfold E15036; decide))

theorem not_33706_1553 : ¬ ∀ (α : Type) (op : α → α → α), E33706 op → E1553 op := by
  intro h
  have hb : ¬ E1553 P4 := by unfold E1553; decide
  exact hb (h (Fin 2) P4 (by unfold E33706; decide))

theorem not_6981_4009 : ¬ ∀ (α : Type) (op : α → α → α), E6981 op → E4009 op := by
  intro h
  have hb : ¬ E4009 P10 := by unfold E4009; decide
  exact hb (h (Fin 3) P10 (by unfold E6981; decide))

theorem not_58261_3193 : ¬ ∀ (α : Type) (op : α → α → α), E58261 op → E3193 op := by
  intro h
  have hb : ¬ E3193 P1 := by unfold E3193; decide
  exact hb (h (Fin 2) P1 (by unfold E58261; decide))

theorem not_60021_4402 : ¬ ∀ (α : Type) (op : α → α → α), E60021 op → E4402 op := by
  intro h
  have hb : ¬ E4402 P14 := by unfold E4402; decide
  exact hb (h (Fin 2) P14 (by unfold E60021; decide))

theorem not_62056_1763 : ¬ ∀ (α : Type) (op : α → α → α), E62056 op → E1763 op := by
  intro h
  have hb : ¬ E1763 P1 := by unfold E1763; decide
  exact hb (h (Fin 2) P1 (by unfold E62056; decide))

theorem not_51433_3583 : ¬ ∀ (α : Type) (op : α → α → α), E51433 op → E3583 op := by
  intro h
  have hb : ¬ E3583 P2 := by unfold E3583; decide
  exact hb (h (Fin 2) P2 (by unfold E51433; decide))

theorem not_54106_3715 : ¬ ∀ (α : Type) (op : α → α → α), E54106 op → E3715 op := by
  intro h
  have hb : ¬ E3715 P3 := by unfold E3715; decide
  exact hb (h (Fin 2) P3 (by unfold E54106; decide))

theorem not_54550_1818 : ¬ ∀ (α : Type) (op : α → α → α), E54550 op → E1818 op := by
  intro h
  have hb : ¬ E1818 P1 := by unfold E1818; decide
  exact hb (h (Fin 2) P1 (by unfold E54550; decide))

theorem not_49494_935 : ¬ ∀ (α : Type) (op : α → α → α), E49494 op → E935 op := by
  intro h
  have hb : ¬ E935 P1 := by unfold E935; decide
  exact hb (h (Fin 2) P1 (by unfold E49494; decide))

theorem not_60946_4203 : ¬ ∀ (α : Type) (op : α → α → α), E60946 op → E4203 op := by
  intro h
  have hb : ¬ E4203 P15 := by unfold E4203; decide
  exact hb (h (Fin 3) P15 (by unfold E60946; decide))

theorem not_51340_3602 : ¬ ∀ (α : Type) (op : α → α → α), E51340 op → E3602 op := by
  intro h
  have hb : ¬ E3602 P7 := by unfold E3602; decide
  exact hb (h (Fin 2) P7 (by unfold E51340; decide))

theorem not_35640_1792 : ¬ ∀ (α : Type) (op : α → α → α), E35640 op → E1792 op := by
  intro h
  have hb : ¬ E1792 P7 := by unfold E1792; decide
  exact hb (h (Fin 2) P7 (by unfold E35640; decide))

theorem not_46836_1240 : ¬ ∀ (α : Type) (op : α → α → α), E46836 op → E1240 op := by
  intro h
  have hb : ¬ E1240 P1 := by unfold E1240; decide
  exact hb (h (Fin 2) P1 (by unfold E46836; decide))

theorem not_5665_1857 : ¬ ∀ (α : Type) (op : α → α → α), E5665 op → E1857 op := by
  intro h
  have hb : ¬ E1857 P10 := by unfold E1857; decide
  exact hb (h (Fin 3) P10 (by unfold E5665; decide))

theorem not_55824_1224 : ¬ ∀ (α : Type) (op : α → α → α), E55824 op → E1224 op := by
  intro h
  have hb : ¬ E1224 P1 := by unfold E1224; decide
  exact hb (h (Fin 2) P1 (by unfold E55824; decide))

theorem not_54956_2812 : ¬ ∀ (α : Type) (op : α → α → α), E54956 op → E2812 op := by
  intro h
  have hb : ¬ E2812 P1 := by unfold E2812; decide
  exact hb (h (Fin 2) P1 (by unfold E54956; decide))



end Luotain.NewLaws
