-- Generated by Luotain (https://github.com/anttiluode/Luotain). Core Lean 4, no Mathlib.
set_option maxHeartbeats 1000000
set_option maxRecDepth 100000
set_option linter.unusedVariables false
set_option maxErrors 100000


namespace Luotain.SampleEdges



abbrev E1 {α : Type} (op : α → α → α) : Prop := ∀ x : α, x = x

abbrev E2 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = y

abbrev E24 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op x x) y

abbrev E25 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op x y) x

abbrev E40 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op y y

abbrev E41 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op y z

abbrev E109 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op (op y y) z)

abbrev E166 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op y x) (op x x)

abbrev E203 {α : Type} (op : α → α → α) : Prop := ∀ x : α, x = op (op x (op x x)) x

abbrev E260 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op x y) x) x

abbrev E280 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op y y) x) x

abbrev E318 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op y (op z x)

abbrev E397 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op (op z x) w

abbrev E434 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op y (op x (op z z)))

abbrev E690 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op x (op (op z y) x))

abbrev E710 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op y (op (op x z) y))

abbrev E847 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op (op y y) (op y z))

abbrev E917 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op y (op (op y y) (op x y))

abbrev E945 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op z x) (op x z))

abbrev E1288 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op y (op (op (op x y) y) x)

abbrev E1376 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op (op (op z y) z) z)

abbrev E1469 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x y) (op z (op z x))

abbrev E1636 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x x) (op (op y x) z)

abbrev E1639 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x x) (op (op y y) z)

abbrev E1664 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x y) (op (op z x) x)

abbrev E1726 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y y) (op (op x z) z)

abbrev E2135 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op y y) y) (op x y)

abbrev E2277 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x (op y (op z y))) x

abbrev E2366 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op z (op x x))) z

abbrev E2583 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, x = op (op y (op (op z x) w)) u

abbrev E2685 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op x y) (op z y)) z

abbrev E2724 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y x) (op z z)) x

abbrev E2737 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op y y) (op x y)) y

abbrev E2746 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op y y) (op y y)) x

abbrev E2855 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op x (op x y)) y) x

abbrev E2953 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y (op y y)) z) y

abbrev E2984 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, x = op (op (op y (op z x)) z) w

abbrev E3007 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op y (op z z)) x) x

abbrev E3145 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op y y) x) z) x

abbrev E3277 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x x = op y (op x (op z w))

abbrev E3306 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x y = op x (op x (op x y))

abbrev E3312 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op x (op x (op z y))

abbrev E3313 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op x (op x (op z z))

abbrev E3349 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op y (op x (op z y))

abbrev E3369 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op y (op z (op y w))

abbrev E3476 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op y (op (op x y) z)

abbrev E3493 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op y (op (op z x) z)

abbrev E3520 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op x (op (op y x) z)

abbrev E3557 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op y (op (op y x) z)

abbrev E3590 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op z (op (op x z) x)

abbrev E3682 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op y x) (op z z)

abbrev E3856 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op x y = op (op z w) (op u x)

abbrev E3866 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op x (op x y)) z

abbrev E3939 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op x (op z y)) y

abbrev E3975 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op y (op z y)) x

abbrev E4048 {α : Type} (op : α → α → α) : Prop := ∀ x y z w u : α, op x y = op (op z (op w y)) u

abbrev E4069 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op (op x x) y) z

abbrev E4273 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x (op x x) = op y (op x y)

abbrev E4327 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y x) = op z (op x x)

abbrev E4400 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op x y) = op (op x y) z

abbrev E4402 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op x y) = op (op x z) y

abbrev E4439 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y x) = op (op x z) y

abbrev E4447 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y x) = op (op y y) z

abbrev E4487 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y y) = op (op y z) z

abbrev E4583 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op (op x x) x = op (op x x) y

abbrev E4585 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op (op x x) x = op (op x y) y

abbrev E4615 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x x) y = op (op z x) y

abbrev E4616 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x x) y = op (op z x) z

abbrev E4909 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op y (op x (op x (op y (op x y))))

abbrev E8518 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op y (op x (op (op (op z z) y) x))

abbrev E9183 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op x (op (op y y) (op y (op y y)))

abbrev E11828 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op x (op (op (op y y) z) (op z x))

abbrev E18242 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op y y) (op y (op (op x x) y))

abbrev E20553 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x y) (op (op (op x z) x) x)

abbrev E30204 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op x (op y (op (op x z) y))) x

abbrev E31031 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op x (op (op x y) (op y x))) y

abbrev E31937 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op x (op (op y (op x x)) y)) x

abbrev E32348 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op y (op (op y (op z z)) y)) x

abbrev E37243 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op x (op y (op y y))) x) x

abbrev E38225 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op y (op (op x x) x)) x) y

abbrev E39148 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, x = op (op (op (op y x) (op y y)) x) x

abbrev E39160 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, x = op (op (op (op y x) (op y z)) x) z

abbrev E42471 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x x = op y (op x (op (op y y) x))

abbrev E42642 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x y = op x (op x (op (op z w) y))

abbrev E45057 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op x (op (op (op y x) y) z)

abbrev E45987 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op y x) (op z (op x y))

abbrev E46823 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x x = op (op x y) (op (op y z) y)

abbrev E49721 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x y = op (op x (op z (op y y))) y

abbrev E50656 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op x y = op (op y (op (op x x) y)) x

abbrev E52067 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x x = op (op (op x (op x y)) z) w

abbrev E53888 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op x y) = op x (op z (op z y))

abbrev E56523 {α : Type} (op : α → α → α) : Prop := ∀ x y z w : α, op x (op x y) = op (op x (op z w)) y

abbrev E57635 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op x (op y x) = op (op (op z z) z) y

abbrev E58244 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op (op x x) y = op x (op x (op x x))

abbrev E58874 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x y) z = op z (op y (op y z))

abbrev E60324 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x y) y = op (op x z) (op y x)

abbrev E60384 {α : Type} (op : α → α → α) : Prop := ∀ x y z : α, op (op x y) y = op (op z x) (op z z)

abbrev E61951 {α : Type} (op : α → α → α) : Prop := ∀ x y : α, op (op x y) x = op (op (op y y) x) y



def P0_tbl : List Nat := [0, 1, 0, 1]
def P0 (a b : Fin 2) : Fin 2 := ⟨(P0_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P1_tbl : List Nat := [0, 2, 4, 1, 3, 4, 1, 3, 0, 2, 3, 0, 2, 4, 1, 2, 4, 1, 3, 0, 1, 3, 0, 2, 4]
def P1 (a b : Fin 5) : Fin 5 := ⟨(P1_tbl.getD (5 * a.val + b.val) 0) % 5, Nat.mod_lt _ (by decide)⟩

def P2_tbl : List Nat := [0, 0, 1, 0]
def P2 (a b : Fin 2) : Fin 2 := ⟨(P2_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P3_tbl : List Nat := [0, 3, 1, 4, 2, 3, 1, 4, 2, 0, 1, 4, 2, 0, 3, 4, 2, 0, 3, 1, 2, 0, 3, 1, 4]
def P3 (a b : Fin 5) : Fin 5 := ⟨(P3_tbl.getD (5 * a.val + b.val) 0) % 5, Nat.mod_lt _ (by decide)⟩

def P4_tbl : List Nat := [0, 0, 0, 0]
def P4 (a b : Fin 2) : Fin 2 := ⟨(P4_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P5_tbl : List Nat := [0, 0, 1, 1]
def P5 (a b : Fin 2) : Fin 2 := ⟨(P5_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P6_tbl : List Nat := [0, 0, 0, 0, 0, 0, 0, 1, 0]
def P6 (a b : Fin 3) : Fin 3 := ⟨(P6_tbl.getD (3 * a.val + b.val) 0) % 3, Nat.mod_lt _ (by decide)⟩

def P7_tbl : List Nat := [0, 1, 2, 3, 4, 2, 3, 4, 0, 1, 4, 0, 1, 2, 3, 1, 2, 3, 4, 0, 3, 4, 0, 1, 2]
def P7 (a b : Fin 5) : Fin 5 := ⟨(P7_tbl.getD (5 * a.val + b.val) 0) % 5, Nat.mod_lt _ (by decide)⟩

def P8_tbl : List Nat := [0, 1, 0, 0]
def P8 (a b : Fin 2) : Fin 2 := ⟨(P8_tbl.getD (2 * a.val + b.val) 0) % 2, Nat.mod_lt _ (by decide)⟩

def P9_tbl : List Nat := [0, 2, 1, 1, 0, 2, 2, 1, 0]
def P9 (a b : Fin 3) : Fin 3 := ⟨(P9_tbl.getD (3 * a.val + b.val) 0) % 3, Nat.mod_lt _ (by decide)⟩



theorem imp_8518_1 : ∀ (α : Type) (op : α → α → α), E8518 op → E1 op := by
  intro α op h
  unfold E8518 at h
  unfold E1
  intro x
  grind

theorem imp_690_8518 : ∀ (α : Type) (op : α → α → α), E690 op → E8518 op := by
  intro α op h
  unfold E690 at h
  unfold E8518
  intro x y z
  grind

theorem not_8518_1639 : ¬ ∀ (α : Type) (op : α → α → α), E8518 op → E1639 op := by
  intro h
  have hb : ¬ E1639 P0 := by unfold E1639; decide
  exact hb (h (Fin 2) P0 (by unfold E8518; decide))

theorem imp_18242_1 : ∀ (α : Type) (op : α → α → α), E18242 op → E1 op := by
  intro α op h
  unfold E18242 at h
  unfold E1
  intro x
  grind

theorem not_18242_166 : ¬ ∀ (α : Type) (op : α → α → α), E18242 op → E166 op := by
  intro h
  have hb : ¬ E166 P1 := by unfold E166; decide
  exact hb (h (Fin 5) P1 (by unfold E18242; decide))

theorem imp_9183_1 : ∀ (α : Type) (op : α → α → α), E9183 op → E1 op := by
  intro α op h
  unfold E9183 at h
  unfold E1
  intro x
  grind

theorem imp_847_9183 : ∀ (α : Type) (op : α → α → α), E847 op → E9183 op := by
  intro α op h
  unfold E847 at h
  unfold E9183
  intro x y
  grind

theorem not_9183_2685 : ¬ ∀ (α : Type) (op : α → α → α), E9183 op → E2685 op := by
  intro h
  have hb : ¬ E2685 P2 := by unfold E2685; decide
  exact hb (h (Fin 2) P2 (by unfold E9183; decide))

theorem imp_38225_1 : ∀ (α : Type) (op : α → α → α), E38225 op → E1 op := by
  intro α op h
  unfold E38225 at h
  unfold E1
  intro x
  grind

theorem not_38225_2583 : ¬ ∀ (α : Type) (op : α → α → α), E38225 op → E2583 op := by
  intro h
  have hb : ¬ E2583 P3 := by unfold E2583; decide
  exact hb (h (Fin 5) P3 (by unfold E38225; decide))

theorem imp_57635_4273 : ∀ (α : Type) (op : α → α → α), E57635 op → E4273 op := by
  intro α op h
  unfold E57635 at h
  unfold E4273
  intro x y
  grind

theorem not_57635_710 : ¬ ∀ (α : Type) (op : α → α → α), E57635 op → E710 op := by
  intro h
  have hb : ¬ E710 P4 := by unfold E710; decide
  exact hb (h (Fin 2) P4 (by unfold E57635; decide))

theorem imp_58244_4583 : ∀ (α : Type) (op : α → α → α), E58244 op → E4583 op := by
  intro α op h
  unfold E58244 at h
  unfold E4583
  intro x y
  grind

theorem not_58244_3975 : ¬ ∀ (α : Type) (op : α → α → α), E58244 op → E3975 op := by
  intro h
  have hb : ¬ E3975 P2 := by unfold E3975; decide
  exact hb (h (Fin 2) P2 (by unfold E58244; decide))

theorem imp_61951_1 : ∀ (α : Type) (op : α → α → α), E61951 op → E1 op := by
  intro α op h
  unfold E61951 at h
  unfold E1
  intro x
  grind

theorem not_61951_2366 : ¬ ∀ (α : Type) (op : α → α → α), E61951 op → E2366 op := by
  intro h
  have hb : ¬ E2366 P4 := by unfold E2366; decide
  exact hb (h (Fin 2) P4 (by unfold E61951; decide))

theorem imp_31031_1 : ∀ (α : Type) (op : α → α → α), E31031 op → E1 op := by
  intro α op h
  unfold E31031 at h
  unfold E1
  intro x
  grind

theorem not_31031_397 : ¬ ∀ (α : Type) (op : α → α → α), E31031 op → E397 op := by
  intro h
  have hb : ¬ E397 P5 := by unfold E397; decide
  exact hb (h (Fin 2) P5 (by unfold E31031; decide))

theorem imp_31937_1 : ∀ (α : Type) (op : α → α → α), E31937 op → E1 op := by
  intro α op h
  unfold E31937 at h
  unfold E1
  intro x
  grind

theorem imp_25_31937 : ∀ (α : Type) (op : α → α → α), E25 op → E31937 op := by
  intro α op h
  unfold E25 at h
  unfold E31937
  intro x y
  grind

theorem not_31937_917 : ¬ ∀ (α : Type) (op : α → α → α), E31937 op → E917 op := by
  intro h
  have hb : ¬ E917 P5 := by unfold E917; decide
  exact hb (h (Fin 2) P5 (by unfold E31937; decide))

theorem imp_11828_1 : ∀ (α : Type) (op : α → α → α), E11828 op → E1 op := by
  intro α op h
  unfold E11828 at h
  unfold E1
  intro x
  grind

theorem not_11828_1288 : ¬ ∀ (α : Type) (op : α → α → α), E11828 op → E1288 op := by
  intro h
  have hb : ¬ E1288 P2 := by unfold E1288; decide
  exact hb (h (Fin 2) P2 (by unfold E11828; decide))

theorem imp_45057_1 : ∀ (α : Type) (op : α → α → α), E45057 op → E1 op := by
  intro α op h
  unfold E45057 at h
  unfold E1
  intro x
  grind

theorem imp_1636_45057 : ∀ (α : Type) (op : α → α → α), E1636 op → E45057 op := by
  intro α op h
  unfold E1636 at h
  unfold E45057
  intro x y z
  grind

theorem not_45057_3520 : ¬ ∀ (α : Type) (op : α → α → α), E45057 op → E3520 op := by
  intro h
  have hb : ¬ E3520 P6 := by unfold E3520; decide
  exact hb (h (Fin 3) P6 (by unfold E45057; decide))

theorem imp_42642_3306 : ∀ (α : Type) (op : α → α → α), E42642 op → E3306 op := by
  intro α op h
  unfold E42642 at h
  unfold E3306
  intro x y
  have s0 : ∀ v2 v3 v0 v1 : α, (op v0 v1) = (op v0 (op v0 (op (op v2 v3) v1))) := by intros; grind
  have s1 : (op x y) = (op x y) := by grind
  have s2 : (op x (op x y)) = (op x (op x y)) := by grind
  have s3 : (op x (op x (op x y))) = (op x (op x (op x y))) := by grind
  have s4 : ∀ v0 v1 : α, (op v0 v1) = (op v0 (op v0 (op (op x y) v1))) := by intros; grind
  have s5 : ∀ v0 v1 : α, (op v1 (op v1 (op (op x y) v0))) = (op v1 (op (op x y) (op (op x y) v0))) := by intros; grind
  have s6 : ∀ v0 v1 : α, (op v1 (op (op x y) (op (op x y) v0))) = (op v1 v0) := by intros; grind
  have s7 : ∀ v0 v1 : α, (op v0 (op v0 v1)) = (op v0 (op (op x y) v1)) := by intros; grind
  have s8 : ∀ v0 v1 : α, (op v0 v1) = (op v0 (op v0 (op v0 v1))) := by intros; grind
  have s9 : (op x y) = (op x (op x (op x y))) := by grind
  have s10 : (op x y) = (op x (op x (op x y))) := by grind
  have s11 : (op x y) = (op x (op x (op x y))) := by grind
  grind

theorem imp_3312_42642 : ∀ (α : Type) (op : α → α → α), E3312 op → E42642 op := by
  intro α op h
  unfold E3312 at h
  unfold E42642
  intro x y z w
  grind

theorem not_42642_3590 : ¬ ∀ (α : Type) (op : α → α → α), E42642 op → E3590 op := by
  intro h
  have hb : ¬ E3590 P5 := by unfold E3590; decide
  exact hb (h (Fin 2) P5 (by unfold E42642; decide))

theorem imp_39148_1 : ∀ (α : Type) (op : α → α → α), E39148 op → E1 op := by
  intro α op h
  unfold E39148 at h
  unfold E1
  intro x
  grind

theorem imp_3007_39148 : ∀ (α : Type) (op : α → α → α), E3007 op → E39148 op := by
  intro α op h
  unfold E3007 at h
  unfold E39148
  intro x y
  grind

theorem not_39148_3856 : ¬ ∀ (α : Type) (op : α → α → α), E39148 op → E3856 op := by
  intro h
  have hb : ¬ E3856 P0 := by unfold E3856; decide
  exact hb (h (Fin 2) P0 (by unfold E39148; decide))

theorem imp_4909_1 : ∀ (α : Type) (op : α → α → α), E4909 op → E1 op := by
  intro α op h
  unfold E4909 at h
  unfold E1
  intro x
  grind

theorem not_4909_2855 : ¬ ∀ (α : Type) (op : α → α → α), E4909 op → E2855 op := by
  intro h
  have hb : ¬ E2855 P7 := by unfold E2855; decide
  exact hb (h (Fin 5) P7 (by unfold E4909; decide))

theorem imp_50656_1 : ∀ (α : Type) (op : α → α → α), E50656 op → E1 op := by
  intro α op h
  unfold E50656 at h
  unfold E1
  intro x
  grind

theorem imp_41_50656 : ∀ (α : Type) (op : α → α → α), E41 op → E50656 op := by
  intro α op h
  unfold E41 at h
  unfold E50656
  intro x y
  grind

theorem not_50656_1469 : ¬ ∀ (α : Type) (op : α → α → α), E50656 op → E1469 op := by
  intro h
  have hb : ¬ E1469 P4 := by unfold E1469; decide
  exact hb (h (Fin 2) P4 (by unfold E50656; decide))

theorem imp_42471_1 : ∀ (α : Type) (op : α → α → α), E42471 op → E1 op := by
  intro α op h
  unfold E42471 at h
  unfold E1
  intro x
  grind

theorem not_42471_2737 : ¬ ∀ (α : Type) (op : α → α → α), E42471 op → E2737 op := by
  intro h
  have hb : ¬ E2737 P4 := by unfold E2737; decide
  exact hb (h (Fin 2) P4 (by unfold E42471; decide))

theorem imp_60384_4585 : ∀ (α : Type) (op : α → α → α), E60384 op → E4585 op := by
  intro α op h
  unfold E60384 at h
  unfold E4585
  intro x y
  grind

theorem not_60384_2953 : ¬ ∀ (α : Type) (op : α → α → α), E60384 op → E2953 op := by
  intro h
  have hb : ¬ E2953 P4 := by unfold E2953; decide
  exact hb (h (Fin 2) P4 (by unfold E60384; decide))

theorem imp_58874_4615 : ∀ (α : Type) (op : α → α → α), E58874 op → E4615 op := by
  intro α op h
  unfold E58874 at h
  unfold E4615
  intro x y z
  grind

theorem imp_3349_58874 : ∀ (α : Type) (op : α → α → α), E3349 op → E58874 op := by
  intro α op h
  unfold E3349 at h
  unfold E58874
  intro x y z
  grind

theorem not_58874_1726 : ¬ ∀ (α : Type) (op : α → α → α), E58874 op → E1726 op := by
  intro h
  have hb : ¬ E1726 P4 := by unfold E1726; decide
  exact hb (h (Fin 2) P4 (by unfold E58874; decide))

theorem imp_30204_203 : ∀ (α : Type) (op : α → α → α), E30204 op → E203 op := by
  intro α op h
  unfold E30204 at h
  unfold E203
  intro x
  grind

theorem imp_2277_30204 : ∀ (α : Type) (op : α → α → α), E2277 op → E30204 op := by
  intro α op h
  unfold E2277 at h
  unfold E30204
  intro x y z
  grind

theorem not_30204_2135 : ¬ ∀ (α : Type) (op : α → α → α), E30204 op → E2135 op := by
  intro h
  have hb : ¬ E2135 P5 := by unfold E2135; decide
  exact hb (h (Fin 2) P5 (by unfold E30204; decide))

theorem imp_20553_1 : ∀ (α : Type) (op : α → α → α), E20553 op → E1 op := by
  intro α op h
  unfold E20553 at h
  unfold E1
  intro x
  grind

theorem imp_1664_20553 : ∀ (α : Type) (op : α → α → α), E1664 op → E20553 op := by
  intro α op h
  unfold E1664 at h
  unfold E20553
  intro x y z
  grind

theorem not_20553_3313 : ¬ ∀ (α : Type) (op : α → α → α), E20553 op → E3313 op := by
  intro h
  have hb : ¬ E3313 P0 := by unfold E3313; decide
  exact hb (h (Fin 2) P0 (by unfold E20553; decide))

theorem imp_46823_1 : ∀ (α : Type) (op : α → α → α), E46823 op → E1 op := by
  intro α op h
  unfold E46823 at h
  unfold E1
  intro x
  grind

theorem not_46823_4048 : ¬ ∀ (α : Type) (op : α → α → α), E46823 op → E4048 op := by
  intro h
  have hb : ¬ E4048 P5 := by unfold E4048; decide
  exact hb (h (Fin 2) P5 (by unfold E46823; decide))

theorem not_52067_4327 : ¬ ∀ (α : Type) (op : α → α → α), E52067 op → E4327 op := by
  intro h
  have hb : ¬ E4327 P5 := by unfold E4327; decide
  exact hb (h (Fin 2) P5 (by unfold E52067; decide))

theorem imp_56523_1 : ∀ (α : Type) (op : α → α → α), E56523 op → E1 op := by
  intro α op h
  unfold E56523 at h
  unfold E1
  intro x
  grind

theorem imp_4402_56523 : ∀ (α : Type) (op : α → α → α), E4402 op → E56523 op := by
  intro α op h
  unfold E4402 at h
  unfold E56523
  intro x y z w
  grind

theorem not_56523_1376 : ¬ ∀ (α : Type) (op : α → α → α), E56523 op → E1376 op := by
  intro h
  have hb : ¬ E1376 P4 := by unfold E1376; decide
  exact hb (h (Fin 2) P4 (by unfold E56523; decide))

theorem imp_49721_1 : ∀ (α : Type) (op : α → α → α), E49721 op → E1 op := by
  intro α op h
  unfold E49721 at h
  unfold E1
  intro x
  grind

theorem imp_3939_49721 : ∀ (α : Type) (op : α → α → α), E3939 op → E49721 op := by
  intro α op h
  unfold E3939 at h
  unfold E49721
  intro x y z
  grind

theorem not_49721_3369 : ¬ ∀ (α : Type) (op : α → α → α), E49721 op → E3369 op := by
  intro h
  have hb : ¬ E3369 P5 := by unfold E3369; decide
  exact hb (h (Fin 2) P5 (by unfold E49721; decide))

theorem not_32348_3557 : ¬ ∀ (α : Type) (op : α → α → α), E32348 op → E3557 op := by
  intro h
  have hb : ¬ E3557 P8 := by unfold E3557; decide
  exact hb (h (Fin 2) P8 (by unfold E32348; decide))

theorem not_39160_4400 : ¬ ∀ (α : Type) (op : α → α → α), E39160 op → E4400 op := by
  intro h
  have hb : ¬ E4400 P9 := by unfold E4400; decide
  exact hb (h (Fin 3) P9 (by unfold E39160; decide))

theorem imp_60324_1 : ∀ (α : Type) (op : α → α → α), E60324 op → E1 op := by
  intro α op h
  unfold E60324 at h
  unfold E1
  intro x
  grind

theorem imp_4439_60324 : ∀ (α : Type) (op : α → α → α), E4439 op → E60324 op := by
  intro α op h
  unfold E4439 at h
  unfold E60324
  intro x y z
  grind

theorem not_60324_2984 : ¬ ∀ (α : Type) (op : α → α → α), E60324 op → E2984 op := by
  intro h
  have hb : ¬ E2984 P4 := by unfold E2984; decide
  exact hb (h (Fin 2) P4 (by unfold E60324; decide))

theorem imp_53888_1 : ∀ (α : Type) (op : α → α → α), E53888 op → E1 op := by
  intro α op h
  unfold E53888 at h
  unfold E1
  intro x
  grind

theorem imp_318_53888 : ∀ (α : Type) (op : α → α → α), E318 op → E53888 op := by
  intro α op h
  unfold E318 at h
  unfold E53888
  intro x y z
  grind

theorem not_53888_945 : ¬ ∀ (α : Type) (op : α → α → α), E53888 op → E945 op := by
  intro h
  have hb : ¬ E945 P4 := by unfold E945; decide
  exact hb (h (Fin 2) P4 (by unfold E53888; decide))

theorem imp_37243_1 : ∀ (α : Type) (op : α → α → α), E37243 op → E1 op := by
  intro α op h
  unfold E37243 at h
  unfold E1
  intro x
  grind

theorem imp_260_37243 : ∀ (α : Type) (op : α → α → α), E260 op → E37243 op := by
  intro α op h
  unfold E260 at h
  unfold E37243
  intro x y
  grind

theorem not_37243_3476 : ¬ ∀ (α : Type) (op : α → α → α), E37243 op → E3476 op := by
  intro h
  have hb : ¬ E3476 P5 := by unfold E3476; decide
  exact hb (h (Fin 2) P5 (by unfold E37243; decide))



end Luotain.SampleEdges
