"""Lean 4 certificates (core Lean only, no Mathlib).

Two kinds of certificate:

  refutation  a finite table that obeys law A and breaks law B, both checked by
              `decide`, which gives the theorem  ¬ (∀ α op, A op → B op).
  proof       ∀ α op, A op → B op, proved by `grind`; when grind cannot find the
              instances on its own, the equations from Vampire's proof are replayed
              as intermediate `have` steps, each closed by `grind`.

Everything is checked by Lean's kernel; nothing here trusts Python or Vampire.
"""
from __future__ import annotations

import re

import numpy as np

from .laws import NAMES, Law, lean_prop

HEADER = """-- Generated by Luotain (https://github.com/anttiluode/Luotain). Core Lean 4, no Mathlib.
set_option maxHeartbeats 1000000
set_option maxRecDepth 100000
set_option linter.unusedVariables false
set_option maxErrors 100000
"""


def law_def(law: Law) -> str:
    return f"abbrev E{law.id} {{α : Type}} (op : α → α → α) : Prop := {lean_prop(law)}"


# ----------------------------------------------------------------------------- probes

def table_def(name: str, T: np.ndarray) -> str:
    n = len(T)
    entries = ", ".join(str(int(v)) for v in T.reshape(-1))
    return (f"def {name}_tbl : List Nat := [{entries}]\n"
            f"def {name} (a b : Fin {n}) : Fin {n} := ⟨({name}_tbl.getD ({n} * a.val + b.val) 0) % {n}, "
            f"Nat.mod_lt _ (by decide)⟩")


def refutation(probe: str, n: int, a: Law, b: Law) -> str:
    """¬ (A → B), witnessed by the table `probe` on Fin n."""
    return (f"theorem not_{a.id}_{b.id} : ¬ ∀ (α : Type) (op : α → α → α), E{a.id} op → E{b.id} op := by\n"
            f"  intro h\n"
            f"  have hb : ¬ E{b.id} {probe} := by unfold E{b.id}; decide\n"
            f"  exact hb (h (Fin {n}) {probe} (by unfold E{a.id}; decide))")


# ----------------------------------------------------------------------------- proofs

def _blocks(proof_text: str) -> list[str]:
    """The fof(...) blocks of a TPTP derivation, each with balanced parentheses."""
    out, i = [], 0
    while True:
        i = proof_text.find("fof(", i)
        if i < 0:
            return out
        depth, j = 0, i + 3
        while j < len(proof_text):
            if proof_text[j] == "(":
                depth += 1
            elif proof_text[j] == ")":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        out.append(" ".join(proof_text[i:j + 1].split()))
        i = j + 1


def _split_top(s: str) -> list[str]:
    """Split 'a,b,c' at top-level commas."""
    parts, depth, cur = [], 0, []
    for ch in s:
        if ch == "," and depth == 0:
            parts.append("".join(cur))
            cur = []
            continue
        depth += ch == "("
        depth -= ch == ")"
        cur.append(ch)
    parts.append("".join(cur))
    return parts


def _strip_parens(s: str) -> str:
    s = s.strip()
    while s.startswith("(") and s.endswith(")"):
        depth = 0
        for k, ch in enumerate(s):
            depth += ch == "("
            depth -= ch == ")"
            if depth == 0 and k < len(s) - 1:
                return s
        s = s[1:-1].strip()
    return s


def _tptp_to_lean(s: str, names: dict[str, str]) -> str:
    """m(a,b) -> (op a b); variables X3 -> v3; Skolem constants -> the goal's variables."""
    s = s.replace(" ", "")
    out, i = [], 0
    while i < len(s):
        if s.startswith("m(", i):
            out.append("(op ")
            i += 2
        elif s[i] == ",":
            out.append(" ")
            i += 1
        elif s[i] == ")":
            out.append(")")
            i += 1
        else:
            j = i
            while j < len(s) and (s[j].isalnum() or s[j] == "_"):
                j += 1
            tok = s[i:j]
            if not tok:
                raise ValueError(f"unexpected {s[i:]!r}")
            if tok in names:
                out.append(names[tok])
            elif tok.startswith("X") and tok[1:].isdigit():
                out.append("v" + tok[1:])
            else:
                raise ValueError(f"unknown symbol {tok!r}")
            i = j
    return "".join(out)


def vampire_steps(proof_text: str) -> list[str]:
    """The equations Vampire derived, as Lean propositions over `op`, in proof order.

    Skolem constants of the negated goal become the goal's own variables (x, y, ...),
    which are in scope after `intros`; definitions Vampire introduced (sF..) are
    expanded.  Disequalities and $false are dropped: the last equation derived is the
    goal instance, and grind closes the goal from it."""
    names: dict[str, str] = {}
    defs: dict[str, str] = {}
    steps: list[str] = []
    for blk in _blocks(proof_text):
        inner = blk[4:-1]
        parts = _split_top(inner)
        if len(parts) < 3:
            continue
        role, formula, source = parts[1].strip(), _strip_parens(parts[2]), ",".join(parts[3:])
        for xv, sk in re.findall(r"skolemize\(X(\d+),(sK\d+)\)", source):
            names[sk] = NAMES[int(xv)]
        if role == "definition":
            m = re.match(r"^(sF\d+)\s*=\s*(.*)$", formula)
            if m:
                defs[m.group(1)] = m.group(2)
            continue
        if role != "plain" or "$false" in formula or "!=" in formula or "|" in formula or "&" in formula:
            continue
        vs = []
        m = re.match(r"^!\s*\[([^\]]*)\]\s*:\s*(.*)$", formula)
        if m:
            vs = [v.strip() for v in m.group(1).split(",") if v.strip()]
            formula = _strip_parens(m.group(2))
        if formula.count("=") != 1:
            continue
        for _ in range(10):                       # expand introduced definitions
            for k, v in defs.items():
                formula = re.sub(rf"\b{k}\b", v, formula)
        if "sF" in formula:
            continue
        lhs, rhs = (p.strip() for p in formula.split("="))
        try:
            L, R = _tptp_to_lean(lhs, names), _tptp_to_lean(rhs, names)
        except ValueError:
            continue
        binder = f"∀ {' '.join('v' + v[1:] for v in vs)} : α, " if vs else ""
        steps.append(f"{binder}{L} = {R}")
    return steps


def proof(a: Law, b: Law, steps: list[str] | None = None) -> str:
    goal_vars = " ".join(NAMES[i] for i in range(b.nvars))
    lines = [f"theorem imp_{a.id}_{b.id} : ∀ (α : Type) (op : α → α → α), E{a.id} op → E{b.id} op := by",
             f"  intro α op h",
             f"  unfold E{a.id} at h",
             f"  unfold E{b.id}",
             f"  intro {goal_vars}"]
    for k, s in enumerate(steps or []):
        tac = "intros; grind" if s.startswith("∀") else "grind"
        lines.append(f"  have s{k} : {s} := by {tac}")
    lines.append("  grind")
    return "\n".join(lines)
